### ISSUE TITLE
How can I add krb5 CRD into the installer when new install?

### ISSUE THREAD

**Issue by noname1314** [kurokobo/awx-on-k3s#100]
Hi,

I have installed krb5 package in local OS. However, following different guideline that it is hard to mount krb5 into the container.

Any way I can include the krb5 into the container to able to use the local for Windows Host authentication?

Regards,
Eric Cheng

**Comment by kurokobo** [comment]
@noname1314 
Hi,
Just to confirm, you want to run your Job Template against some Windows-based hosts with Kerberos authentication using a domain user, right?
This page describes how to implement this in AAC, but you want to know how to modify `/etc/krb5.conf` in the container in AWX?
<https://docs.ansible.com/automation-controller/latest/html/administration/kerberos_auth.html>

**Comment by noname1314** [comment]
@kurokobo 

Two purpose I would like to do in AWX:
1. Want to connect AWX by using Windows credential to login AWX
2. When running Job Template, calling Windows Host with Kerberos authentication using a domain user.

Because in old docker platform (AWX 8.0) implementation, I can use krb5 and AWX able to connect to Windows Jump Host successfully. However, in K3S world, it doesn't work.

I have reference your article from official website but the root cause is K3S container cannot get /etc/krb5.conf. So, I may need to add CRD reference to ensure the Job Template container able to connect Windows Jump Host with Kerberos authentication...

**Comment by noname1314** [comment]
@kurokobo 

I tried to visit [the article](https://github.com/ansible/awx/issues/9807#issuecomment-819014975) for install, but failed.

Anyway just integrate those setup into the installer and able for mounting krb5 once able to deploy?

**Comment by kurokobo** [comment]
@noname1314 
Hi, thanks for updating. I understand your situation.

> 1. Want to connect AWX by using Windows credential to login AWX

For this purpose, I have an experience that using my Active Directory as a LDAP server to login AWX. AD works well as LDAP or LDAPS server for AWX as expected, but I think technically this is not Kerberos authentication.
In my understanding, the current implementation of AWX does not have an ability to authenticate using Kerberos. Refer the list of supported authentication backend: https://github.com/ansible/awx/blob/21.2.0/awx/settings/defaults.py#L360-L379

Thus, if it's ok for you to use AD as an LDAP/LDAPS server without Kerberos, I believe your requirements can be met.

> 2. When running Job Template, calling Windows Host with Kerberos authentication using a domain user.

I've never tried that, but I think this can be achieved. My understanding is that `kinit` is executed in EE each time the playbook is invoked. Therefore, I think it is the EE container that should mount `krb5.conf`, not the Task container as commented in the article you mentioned.

I can't give you detailed instructions right away, but the workflow will probably be as follows.

1. Create new ConfigMap that includes your `krb5.conf`.
2. Add new Container Group using customized pod spec that includes reference for your ConfigMap in `volumes`, and `volumeMount` that refer `volumes`.
   - Official instruction about customized pod spec: <https://docs.ansible.com/ansible-tower/latest/html/administration/external_execution_envs.html#customize-the-pod-spec>
   - Similar instruction is also available in my guide: https://github.com/kurokobo/awx-on-k3s/tree/main/containergroup#create-container-group
3. Configure your Job Template to use your brand new Container Group.

**Comment by noname1314** [comment]
@kurokobo 

After created container group & ConfigMap, still not work. It is required to install krb5 package into EE for execution?

Kept same error that still not able to contact KDC by initial credential. Any idea?

**Comment by kurokobo** [comment]
@noname1314 
The packages for Kerberos are bundled in `awx-ee:latest`, so it should work.

```bash
$ kubectl run awx-ee --restart=Never -it --rm --command /usr/bin/bash --image=quay.io/ansible/awx-ee:latest -- -c "rpm -qa | grep krb5"
krb5-libs-1.18.2-20.el8.x86_64
krb5-workstation-1.18.2-20.el8.x86_64
```

Could you provide actual pod spec for your container group, manifest for configmap, and logs?
You can also debug this by pausing your Job Template using `ansible.builtin.pause` module in your playbook and get shell of the EE by `kubectl exec`.

Anyway I'll try this in this weekend in my labo😃

**Comment by kurokobo** [comment]
Hmm, I tested it briefly and it worked fine for me. I will add the guide for this over the weekend.

**Comment by kurokobo** [comment]
@noname1314 
Hi, I've added new guide to use kerberos auth in AWX: https://github.com/kurokobo/awx-on-k3s/blob/main/tips/use-kerberos.md
Please try it out 😃

**Comment by kurokobo** [comment]
@noname1314 
There are two ways.

### Add custom DNS configuration to specific Container Group

Append following three lines to your custom pod spec for your Container Group.

```yaml
...
spec:
  serviceAccountName: default
  automountServiceAccountToken: false
  containers:
    - image: 'quay.io/ansible/awx-ee:latest'
      ...
      volumeMounts:
        - name: awx-kerberos-volume
          mountPath: /etc/krb5.conf
          subPath: krb5.conf
  dnsConfig:     👈👈👈
    nameservers:     👈👈👈
      - 172.31.17.40     👈👈👈
  volumes:
    ...
```

Your DNS server `172.31.17.40` will added to `/etc/resolv.conf` in your EE.

### Add forwarder for CoreDNS for K3s (Cluster-wide configuration)

If you want to add DNS settings across your cluster of K3s, you can configure CoreDNS forwarders by following [step 3, 4, and 5 of this guide](https://github.com/kurokobo/awx-on-k3s/blob/main/tips/expose-hosts.md).

There is no change in `/etc/resolv.conf` in EE, but querying `10.43.0.10` will also query `172.31.17.40` internally.

**Comment by noname1314** [comment]
@kurokobo 

Finally add the pod configuration "dnsConfig: Default" and seems work now.

**Comment by kurokobo** [comment]
Thanks for updating. Closing this issue.
