### ISSUE TITLE
Some help please

### ISSUE THREAD

**Issue by GregoryMachin** [kurokobo/awx-on-k3s#120]
## Environment

- OS: Ubuntu 22.04
- Kubernetes/K3s: v1.24.3+k3s1
- AWX Operator: 0.25.0

## Description
New to Kubernetes/K3s, Ansible, and AWX, so need some help please.
- How can I view the AWX log files, I'm trying to debug some issues:
- - When creating a project the playbook directory don't display the new directories I created. 
- - How can I change the hostname or do I need to rebuild.
- - I have configured LDAP (with Active Directory) authentication but I can't login I get "Invalid username or password. Please try again." the same username and password work in other applications.

## Step to Reproduce

1. projects ...
2. Add  ...
3. Name = test...
4. Description = blaa...
5. Organization = Default
6. Execution Env = AWX EE
7. Source Control Type = Manual
8. Choose a Playbook Directory = nothing
9.

thanks
Greg

**Comment by kurokobo** [comment]
@GregoryMachin 
Hi, if you have any questions about basic usage of AWX or AWX Operator, there are good places to ask; [refer "Get Involved" section](https://github.com/ansible/awx-operator#get-involved) then join in and ask your question on IRC channel or mailing list.

> How can I view the AWX log files, I'm trying to debug some issues:

Refer [my troubleshooting guide to get logs](https://github.com/kurokobo/awx-on-k3s/blob/main/tips/troubleshooting.md#investigate-logs-of-the-containers-inside-the-pods).

> When creating a project the playbook directory don't display the new directories I created.

Creating directory under `/data/projects` like `/data/projects/my-manual-project` and place your playbook there.
Then create new project with "Manual" type. If your directory isn't listed, try _"super reload"_ing your browser or clearing browser cache.

> How can I change the hostname or do I need to rebuild.

If you mean you want to change the URL for your AWX, simply re-create your cert files, modify `awx.yaml`, and `kubectl apply -k base` again.

> I have configured LDAP (with Active Directory) authentication but I can't login I get "Invalid username or password. Please try again." the same username and password work in other applications.

Configuring LDAP with AD is a bit complicated, refer [the official guide](https://docs.ansible.com/automation-controller/latest/html/administration/ldap_auth.html), [KB by Red Hat](https://access.redhat.com/solutions/3684231), or [my blog (japanese)](https://blog.kurokobo.com/archives/4085).

**Comment by GregoryMachin** [comment]
@kurokobo 
Thanks for the fast response .
Once I had the logs I could figure out the LDAP issues, and the _"super reload"_ing the Brower helped. 

Regards
Greg
