### ISSUE TITLE
⚠️ Any updates for this repository will be delayed due to family matters. Thanks for your understanding.

### ISSUE THREAD

**Issue by kurokobo** [kurokobo/awx-on-k3s#126]
I'm currently on paternity leave until Aug. 2023🍼👶

**UPDATE**: My paternity leave may be extended until Apr. 2024🍼👶

**UPDATE**: My paternity leave may be extended again, until May. 2024🍼👶

**Comment by Mocem1** [comment]
Congratulations!

Thank you for all your effort so far.

**Comment by vrubiolo** [comment]
Yes, seconded! Enjoy this time with family, those are precious moments :smile: 

And thanks again for providing this great service to the community :+1:

**Comment by jheinitz** [comment]
Enjoy your time with the baby!

Am Di., 6. Sept. 2022 um 20:42 Uhr schrieb kurokobo <
***@***.***>:

**Comment by smccloud** [comment]
Congrats.  I created my bug report knowing your response will be delayed and I will be trying to solve it myself (and updating it with anything I find).

**Comment by kurokobo** [comment]
@drlamb Thanks, it's enabled now 😃

**Comment by jelly-is-bean** [comment]
Thank you for this repo... I have used it with a minor alteration for ACME provider as Zerossl and DNS as Route53. Congrads on the family expansion

**Comment by kurokobo** [comment]
I ended my paternity leave and returned to my day job 😃 
I may have rather had more time during my paternity leave, but whatever the case, thank you for your understanding and cooperation!
