### ISSUE TITLE
storageclass.storage.k8s.io "awx-postgres-volume" not found

### ISSUE THREAD

**Issue by khain0** [kurokobo/awx-on-k3s#127]
## Environment

- OS: Debian 11
- Kubernetes/K3s: k3s version v1.24.4+k3s1 (c3f830e9)
- AWX Operator: 0.28.0

## Description
AWX deployment hangs on 
TASK [installer : Wait for Database to initialize if managed DB] ***************
task path: /opt/ansible/roles/installer/tasks/database_configuration.yml:206

## Step to Reproduce

1.  Deploy AWX operator
cd ~
git clone https://github.com/ansible/awx-operator.git
cd awx-operator
git checkout 0.28.0
export NAMESPACE=awx
make deploy
kubectl -n awx get all

2. Prepare deployment of AWX
cd ~
git clone https://github.com/kurokobo/awx-on-k3s.git
cd awx-on-k3s
git checkout 0.28.0
AWX_HOST="awx.example.com"
openssl req -x509 -nodes -days 3650 -newkey rsa:2048 -out ./base/tls.crt -keyout ./base/tls.key -subj "/CN=${AWX_HOST}/O=${AWX_HOST}" -addext "subjectAltName = DNS:${AWX_HOST}"
Change password for AWX admin and postgres in base/kustomization.yaml (mentioned in readme)
Change FQDN for awx in base/awx.yaml (mentioned in readme)

3. Create folders
sudo mkdir -p /data/postgres-13
sudo mkdir -p /data/projects
sudo chmod 755 /data/postgres-13
sudo chown 1000:0 /data/projects

4. Deploy AWX
kubectl apply -k base
kubectl -n awx logs -f deployments/awx-operator-controller-manager -c awx-manager

## Actual result
kubectl -n awx logs -f deployments/awx-operator-controller-manager -c awx-manager hangs on 
TASK [installer : Wait for Database to initialize if managed DB] ***************
task path: /opt/ansible/roles/installer/tasks/database_configuration.yml:206

-------------------------------------------------------------------------------
{"level":"info","ts":1662973518.7814083,"logger":"proxy","msg":"cache miss: /v1, Kind=PodList err-Index with name field:status.phase does not exist"}
{"level":"info","ts":1662973525.3748915,"logger":"proxy","msg":"cache miss: /v1, Kind=PodList err-Index with name field:status.phase does not exist"}
{"level":"info","ts":1662973531.96652,"logger":"proxy","msg":"cache miss: /v1, Kind=PodList err-Index with name field:status.phase does not exist"}
{"level":"info","ts":1662973538.5607095,"logger":"proxy","msg":"cache miss: /v1, Kind=PodList err-Index with name field:status.phase does not exist"}
{"level":"info","ts":1662973545.1936836,"logger":"proxy","msg":"cache miss: /v1, Kind=PodList err-Index with name field:status.phase does not exist"}

Portainer shows events warning for awx namaspace:
PersistentVolumeClaim | Warning | storageclass.storage.k8s.io "awx-postgres-volume" not found
0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.

Portainer shows application state:
awx-postgres-13-0 | postgres | postgres:13 | IfNotPresent | Terminated

No logs available for application awx-postgres-13-0 in Portainer

## Expected result
kubectl -n awx logs -f deployments/awx-operator-controller-manager -c awx-manager ends with
----- Ansible Task Status Event StdOut (awx.ansible.com/v1beta1, Kind=AWX, awx/awx) -----
PLAY RECAP *********************************************************************
localhost                  : ok=71   changed=0    unreachable=0    failed=0    skipped=48   rescued=0    ignored=1

**Comment by kurokobo** [comment]
Could you please paste the output of following commands?

```bash
kubectl get pv
kubectl -n awx get pvc
```

**Comment by khain0** [comment]
kubectl get pv
`NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS     CLAIM                                    STORAGECLASS          REASON   AGE
awx-postgres-volume                        8Gi        RWO            Retain           Released   awx/postgres-awx-postgres-0              awx-postgres-volume            90d
awx-projects-volume                        2Gi        RWO            Retain           Released   awx/awx-projects-claim                   awx-projects-volume            90d
awx-postgres-13-volume                     8Gi        RWO            Retain           Released   awx/postgres-13-awx-postgres-13-0        awx-postgres-volume            16h`

kubectl -n awx get pvc
`NAME                            STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS          AGE
awx-projects-claim              Pending                                      awx-projects-volume   74s
postgres-13-awx-postgres-13-0   Pending                                      awx-postgres-volume   33s`

Probably I have some old pv from previous build (age 90d). How to get rid of this?

**Comment by khain0** [comment]
I removed pv and pvc, hence new were created, but I got other error:
`PLAY RECAP *********************************************************************
localhost                  : ok=60   changed=6    unreachable=0    failed=1    skipped=32   rescued=0    ignored=0


----------
{"level":"error","ts":1662983457.2028313,"msg":"Reconciler error","controller":"awx-controller","object":{"name":"awx","namespace":"awx"},"namespace":"awx","name":"awx","reconcileID":"a23bdc51-c7f6-4631-a0f3-c892ec8460db","error":"event runner on failed","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:234"}
{"level":"info","ts":1662983461.7670424,"logger":"logging_event_handler","msg":"[playbook task start]","name":"awx","namespace":"awx","gvk":"awx.ansible.com/v1beta1, Kind=AWX","event_type":"playbook_on_task_start","job":"6965677511332088916","EventData.Name":"installer : Check for presence of Deployment"}

--------------------------- Ansible Task StdOut -------------------------------

TASK [installer : Check for presence of Deployment] ****************************
task path: /opt/ansible/roles/installer/tasks/main.yml:2

-------------------------------------------------------------------------------
E0912 11:51:16.010738       7 leaderelection.go:330] error retrieving resource lock awx/awx-operator: Get "https://10.43.0.1:443/api/v1/namespaces/awx/configmaps/awx-operator": context deadline exceeded
I0912 11:51:16.010945       7 leaderelection.go:283] failed to renew lease awx/awx-operator: timed out waiting for the condition
{"level":"error","ts":1662983476.0110943,"logger":"cmd","msg":"Proxy or operator exited with error.","Namespace":"awx","error":"leader election lost","stacktrace":"github.com/operator-framework/operator-sdk/internal/cmd/ansible-operator/run.NewCmd.func1\n\t/workspace/internal/cmd/ansible-operator/run/cmd.go:80\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902\nmain.main\n\t/workspace/cmd/ansible-operator/main.go:40\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
`

**Comment by khain0** [comment]
Second thing is: how to change port for AWX? Ports 443 and 80 are taken by other container.

**Comment by kurokobo** [comment]
> I removed old pv and pvc, hence new were created and the playbook finished successfully.

Yes, removing old pv and recreating it are correct approach for you. The PV in `Released` state can't be used for new PVC. Refer my comment on https://github.com/kurokobo/awx-on-k3s/issues/10#issuecomment-940975667 for details about PV and PVC.

I guess it's the second (or more) attempt for you to deploy AWX on your K3s, so your old PV remains as `Released` state and K3s can't bind it for your new PVC.

> Second thing is: how to change port for AWX? Ports 443 and 80 are taken by other container.

If you've specify `ingress_type: ingress` and `hostname` in `awx.yaml`, the confict for the ports never be occurred since K3s routes your traffic by using `HOST` header in your HTTP request. Use hostname (`https://awx.example.com/`) to access your AWX instead of IP address, if you've faced `404 page not found` error.
If you want to use IP address to access your AWX, use `service_type: nodeport` and `nodeport_port` instead of `ingresss_type`: https://github.com/ansible/awx-operator/blob/0.28.0/README.md#service-type

**Comment by khain0** [comment]
The thing is that I have docker and k3s installed on the same node. I have a web page running on docker and when I deploy AWX then webpage is inaccessible via FQDN, so I need to change port for AWX on k3s.
I assume I need to change base/awx.yml as follows:
- add
`service_type: NodePort
  nodeport_port: 30080`

Then AWX will be available with https on 30080 port?

**Comment by kurokobo** [comment]
> The thing is that I have docker and k3s installed on the same node. I have a web page running on docker and when I deploy AWX then webpage is inaccessible via FQDN, so I need to change port for AWX on k3s.

Ah okay, I understand your situation.
Sadly `nodeport` can be used for plain _HTTP_ only. If you specify `nodeport_port: 30080`, your AWX can be accessed `http://x.x.x.x:30080/` via _HTTP_, but cannot be accessed via _HTTPS_.

Technically you can customize your Traefik to use non-default port for https. Refer my comment on https://github.com/kurokobo/awx-on-k3s/issues/85#issuecomment-1151447019, and you should learn about [EntryPoint](https://doc.traefik.io/traefik/routing/entrypoints/) feature for Traefik.

I know that customizing Traefik is a bit complicated and requires some expertise about Traefik, so my recommendation is deploying your AWX on the different host, or changing HTTPS port for your Docker container.

**Comment by khain0** [comment]
Thanks for clarification and guidance. When I get more knowledge about kubernetes I will migrate my web page from docker to kubernetes and use traefik as you mentioned..
