### ISSUE TITLE
AWX Projects folder configuration

### ISSUE THREAD

**Issue by Hillsie** [kurokobo/awx-on-k3s#128]
Hope your family issues are resolved peacefully. 

## Description
With this issue, when creating a new project and using a `source control type`  of `manual`  the location is `/var/lib/awx/projects`, not `/data/projects`. It is also readonly as in not changeable in the ui.

Is this a configuration issue or  bug? Should I add this to the AWX repo? I raised it here as the setup had some changes with the project path in the documentation and I've configured the project location in the way the docs suggest here.

## Environment
k3s version v1.24.4+k3s1 (c3f830e9)
go version go1.18.1
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
AWX 21.5.0 

## Steps to recreate

Create a new project and choose the source control type of `manual`.

**Comment by kurokobo** [comment]
Hi,

> Hope your family issues are resolved peacefully.

Thanks, please don't worry it's not an _issue_ but just a bit busy with childcare👶

> With this issue, when creating a new project and using a source control type of manual the location is /var/lib/awx/projects, not /data/projects. It is also readonly as in not changeable in the ui.
> Is this a configuration issue or bug?

It's designed behavior. In short, your `/data/projects` is mounted as `/var/lib/awx/projects` in AWX.
So if you place your playbook under `/data/projects/my-custom-project/my-playbook.yml`, your AWX detects it as `/var/lib/awx/projects/my-custom-project/my-playbook.yml`.

If your UI doesn't show your directories under `/data/projects` even if you've placed some directories that contain playbooks, simply **reloading your browser** will help you.

Technical details:

- AWX on Kubernetes mounts Persistent Volume (PV) as `/var/lib/awx/projects` through Persistent Volume Claim (PVC) `awx-projects-claim`. This is the designed behavior of AWX Operator if `projects_persistence` is `true` in `awx.yaml`.
- In this guide, the PVC `awx-projects-claim` is designed to refer the PV `awx-projects-volume` that uses `/data/projects` as actual path (this is the `hostPath`-based PV that is useful for single-node cluster)

**Comment by Hillsie** [comment]
> Thanks, please don't worry it's not an issue but just a bit busy with childcarebaby
Lol, good! Normal life is great 

Thanks for the detailed explanation. 

Closing the issue.
