### ISSUE TITLE
Install packages into a pod

### ISSUE THREAD

**Issue by sogithub208** [kurokobo/awx-on-k3s#145]
Hi,
I have installed awx-operator with your documentation with success.
Now i'm facing issues with my existing playbooks. See as below the error message :
/bin/sh: sudo: command not found
When i'm connecting to the pod with shell session, i see that the command sudo is not installed. I need privileges to install it but i can't connect with root user to the pod.
Can you please tell me how i can install it ? Does i need to edit configmap with apt command to make it persistent ? Or how i can do this ?
Best regards
Thanks in advance for your return.

**Comment by kurokobo** [comment]
@sogithub208 
Hi, thanks for using my guide. I think you should to know about _Execution Environment_.
I guess you're trying to invoke tasks to `hosts: localhost` with `become: true`, but `localhost` in AWX's job means not your actual K3s localhost, but the Pod of Execution Environment itself.

So, in any cases, invoking tasks to `localhost` with `become: true` in AWX's job is not required. If it is required, I guess something wrong is tried to be achieved.

- [What's new in Ansible Automation Platform 2: automation execution environments](https://www.ansible.com/blog/whats-new-in-ansible-automation-platform-2-automation-execution-environments)
- [What are Red Hat Ansible Automation Platform automation execution environments?](https://www.redhat.com/en/technologies/management/ansible/automation-execution-environments)

The Pod for Execution Environment can be customized by [Ansible Builder](https://github.com/kurokobo/awx-on-k3s/tree/main/builder), but in the first place, I want to make sure what you are trying todo. Could you provide your goal and actual playbook or tasks you want to run in AWX?

**Comment by sogithub208** [comment]
@kurokobo 
Hi ! thank you ! the problem is solved.
Before this new installation, my plabook was working on an AWX docker installation.
Best regards

**Comment by kurokobo** [comment]
Hi, thanks for updating. Have fun 🤗
