### ISSUE TITLE
Privilege's issue 

### ISSUE THREAD

**Issue by sogithub208** [kurokobo/awx-on-k3s#148]
Hi,
After this new installation, i have another issue with my playbook and i dont found the solution. Do you have some ideas to resolve this error message please ?
<"msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user>
With my older AWX installation on docker i don't meet this problem.
I tried the option allow_world_readable_tmpfiles: true on my playbook without success. It's due to my execution environnement ? Does i have to custom it ? or create another with others configurations ?
Thanks and regards !

**Comment by kurokobo** [comment]
Hi, I can't provide any solutions for you due to lack of information.
Please provide detailed information, not a summary. e.g. your platform, your installation, your execution environment, your playbook, your task, your target host, etc.
