### ISSUE TITLE
"Failed to import the required Python library (kubernetes)" when attempting to backup AWX

### ISSUE THREAD

**Issue by PC-Admin** [kurokobo/awx-on-k3s#159]
## Environment

- OS: Ubuntu 22.04
- Kubernetes/K3s: k3s version v1.24.8+k3s1 (648004e4)
- AWX Operator: 1.1.0

## Description

Hello! I'm trying to make a wrapper for your project which can be found here: https://github.com/PC-Admin/awx-ansible

I've got the latest AWX up and running and was trying to first automate the backup of AWX using AWX. But I've hit a roadblock, I was able to get the manual backup steps here to work: https://github.com/kurokobo/awx-on-k3s/blob/main/backup/README.md

But I've run into trouble getting this running from AWX following these steps: https://github.com/kurokobo/awx-on-k3s/tree/main/backup/ansible

First I copied the custom pod specification into Instance Groups:
![awx-backup-setup1](https://user-images.githubusercontent.com/29645145/206699589-7984ffb2-ffdf-4552-9293-268f92a045ff.jpg)

Secondly I configured this repository as a project:
![awx-backup-setup2](https://user-images.githubusercontent.com/29645145/206700115-3a48ad49-0ce9-43da-9f95-103cf1d9a9f1.jpg)

Thirdly I configure the job template:
![awx-backup-setup3](https://user-images.githubusercontent.com/29645145/206700754-0178947b-d34e-4d01-a8dc-ca40beca656a.jpg)

But when I run the job it fails with:
```
TASK [Create new AWXBackup resource and wait for complete] *********************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'kubernetes'
fatal: [localhost]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/libexec/platform-python"}, "changed": false, "error": "No module named 'kubernetes'", "msg": "Failed to import the required Python library (kubernetes) on automation-job-199-vd9gz's Python /usr/libexec/platform-python. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}

TASK [Clean up failed AWXBackup resource] **************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'kubernetes'
fatal: [localhost]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/libexec/platform-python"}, "changed": false, "error": "No module named 'kubernetes'", "msg": "Failed to import the required Python library (kubernetes) on automation-job-199-vd9gz's Python /usr/libexec/platform-python. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}
```

Any idea what I'm missing here? Sorry if this is a noob question.. :S

**Comment by kurokobo** [comment]
@PC-Admin 
Hi, thanks for reporting.
`/usr/libexec/platform-python` is incorrect python interpreter for `awx-ee` image. I guess you missed `ansible_python_interpreter` variable for `localhost` in your inventory `Pen_Holder`.

Try adding following variables for your `localhost` in `Pen_Holder`, as default `localhost` in default `Demo Inventory` has.

```yaml
ansible_connection: local
ansible_python_interpreter: '{{ ansible_playbook_python }}'
```

![image](https://user-images.githubusercontent.com/2920259/206798971-c8bdcd1a-9570-4a9e-a10e-f2c3507d12c5.png)

**Comment by PC-Admin** [comment]
Thanks for the quick response, that worked. :)

I'll be closing this ticket for now, it could be a good idea to add a note about this to this page: https://github.com/kurokobo/awx-on-k3s/tree/main/backup/ansible#use-with-ansible

**Comment by kurokobo** [comment]
@PC-Admin 
Thanks for updating and providing an idea to improve my guide. That's good idea, I'll add some description for the inventory to be used with my playbook.
Have fun! :)

**Comment by kurokobo** [comment]
Added note for inventory by #167
