### ISSUE TITLE
Job error on container log rotation

### ISSUE THREAD

**Issue by meis4h** [kurokobo/awx-on-k3s#16]
Hi, thanks for this great guide!
 
When running jobs with a large number of hosts we found that we would trigger https://github.com/ansible/awx/issues/10366 which causes the Job in AWX to exit with the message "error" and no summary even through the ee pod would still finish the playbook in the background.

As described in the issue linked above the error occurs when container logs are rotated by the kubelet causing the Kubernetes log stream which AWX uses to fail.

I can confirm that by increasing the maximum container log size as described by this comment https://github.com/ansible/awx/issues/10366#issuecomment-944060894 the issue can be worked around until the root cause is fixed.
We used the following command to update/install K3s with the increased maximum:
```bash
curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="--kubelet-arg "container-log-max-size=150Mi"" sh -
```
Maybe it's worth increasing the maximum even further than 150Mi (from the 10Mi default) for bigger environments.

**Comment by kurokobo** [comment]
Thanks for informing me of that 😃 
Added this information to [the new troubleshooting guide](https://github.com/kurokobo/awx-on-k3s/blob/main/tips/troubleshooting.md#job-failed-with-no-output).
