### ISSUE TITLE
No idea why still not able to install AWx on K3S

### ISSUE THREAD

**Issue by noname1314** [kurokobo/awx-on-k3s#162]
## Environment

- OS: Oracle Linux 8.6
- Kubernetes/K3s:
- k3s version v1.25.4+k3s1 (0dc63334)
go version go1.19.3
- AWX Operator 1.1.2
- AWX 21.10.1
- PostgreSQL 13
- Network access: allowed all outbound traffic (with HTTPS 443)

## Description

[logcaptureFromAWXMgr.txt](https://github.com/kurokobo/awx-on-k3s/files/10225430/logcaptureFromAWXMgr.txt)

![image](https://user-images.githubusercontent.com/22712192/207533897-991df8fd-8903-4a96-a255-6ab2d896ba45.png)

## Step to Reproduce
cd ~
git clone https://github.com/ansible/awx-operator.git
cd awx-operator
git checkout 1.1.2
export NAMESPACE=awx
make deploy
cd ~
git clone https://github.com/kurokobo/awx-on-k3s.git
cd awx-on-k3s
git checkout 1.1.2
(Generate self signed certificate)
sudo mkdir -p /data/postgres-13
sudo mkdir -p /data/projects
sudo chmod 755 /data/postgres-13
sudo chown 1000:0 /data/projects
kubectl apply -k base

**Comment by noname1314** [comment]
@kurokobo Thanks. There has other issue when I want to build Execution Environment:

![image](https://user-images.githubusercontent.com/22712192/208082624-89cfae18-a9c5-45a3-afe8-4072f98caac7.png)

![image](https://user-images.githubusercontent.com/22712192/208082693-955fc2b4-0aed-4e3a-a557-6c5378e1a09a.png)

**Comment by kurokobo** [comment]
@noname1314 
Could you provide full logs and all files (yml and txt)?

**Comment by noname1314** [comment]
@kurokobo

**Comment by noname1314** [comment]
@kurokobo 
[PuttyLog.txt](https://github.com/kurokobo/awx-on-k3s/files/10253111/PuttyLog.txt)

**Comment by noname1314** [comment]
@kurokobo Any idea?

**Comment by kurokobo** [comment]
@noname1314 
Hey do not rush me. I'm not available 24/7 to solve your issue.

**Comment by kurokobo** [comment]
Read #126

**Comment by noname1314** [comment]
@kurokobo 

Sorry to interrupt. I have solved to minimize the necessary package for EE image installation.
