### ISSUE TITLE
[Feature] Setting up Lets Encrypt

### ISSUE THREAD

**Issue by Lvl4Sword** [kurokobo/awx-on-k3s#18]
Rather than setting up a self-signed certificate, it'd be better to setup Lets Encrypt.
Since a domain/sub-domain is already set while configuring, might as well not make a self-signed cert.

**Comment by kurokobo** [comment]
Thanks for sending the future request.

What ACME Challenge Type would you like to use?
`HTTP-01` is simpler, but it requires exposing the kubernetes cluster to the Internet, which raises security concerns.
So I'm a big fan of `DNS-01`, but in any case, I think the cert-manager which is the popular ACME client can coexist well with AWX Operator.

Anyway I'll give it a try :)

**Comment by Lvl4Sword** [comment]
DNS-01 makes sense. Thank you \:\)

**Comment by kurokobo** [comment]
@Lvl4Sword 
Added the guide [`acme/README.md`](https://github.com/kurokobo/awx-on-k3s/tree/main/acme) and added link to this guide in [`README.md`](https://github.com/kurokobo/awx-on-k3s#prepare-required-files) on root of repo.
Feel free to re-open this issue or create new one if you have any concerns. Thanks!
