### ISSUE TITLE
Problem with LDAPS (trust-custom-ca.md)

### ISSUE THREAD

**Issue by chiwuz** [kurokobo/awx-on-k3s#184]
Hello,

I looked at your instructions about trust-custom-ca.md and followed them but I just can't get ldaps to work. Can you please tell me where I can change so that ldaps will not check the certificate.

BR

**Comment by kurokobo** [comment]
I can tell nothing since I don't know your configuration, your try outs and its results.

Sufficient answers require sufficient information to be provided. Do not omit issue templates; provide as much detailed information as possible.

**Comment by chiwuz** [comment]
**ENVIRONMENT**
OS: RHEL 8.7
Kubernetes/K3s: 
  - Client version v1.25.6+k3s1
  - Kustomize version: v4.5.7
AWX Operator: 21.12.0 

First of all, I apologize for the short description of the problem I am having. First I installed Ansible AWX Tower according to your instructions https://github.com/kurokobo/awx-on-k3s. But then I got into the LDAPS configuration because I saw that under TIPS you posted that as well.

I followed the instructions you posted here. However, I still get this error: 
2023-02-17 18:28:48,406 WARNING  [3ad53c0ccde1439bbd2ec32f7d81f007] django_auth_ldap Caught LDAPError while authenticating SIKO1997: SERVER_DOWN({'result': -1, 'desc': "Can't contact LDAP server", 'ctrls': [], 'info': 'error:0A000086:SSL routines::certificate verify failed (unable to get issuer certificate)'})

This is my file awx.yaml:

---

apiVersion: [awx.ansible.com/v1beta1](http://awx.ansible.com/v1beta1)

kind: AWX

metadata:

  name: awx

spec:

  # These parameters are designed for use with:

  # - AWX Operator: 1.2.0

  #   https://github.com/ansible/awx-operator/blob/1.2.0/README.md

  # - AWX: 21.12.0

  #   https://github.com/ansible/awx/blob/21.12.0/INSTALL.md

 

  admin_user: admin

  admin_password_secret: awx-admin-password

 

  ingress_type: ingress

  ingress_tls_secret: awx-secret-tls

  hostname: [t-sena.novakbm.nkbm.si](http://t-sena.novakbm.nkbm.si/)

 

  postgres_configuration_secret: awx-postgres-configuration

 

  postgres_storage_class: awx-postgres-volume

  postgres_storage_requirements:

    requests:

      storage: 8Gi

 

  projects_persistence: true

  projects_existing_claim: awx-projects-claim

 

  postgres_init_container_resource_requirements: {}

  postgres_resource_requirements: {}

  web_resource_requirements: {}

  task_resource_requirements: {}

  ee_resource_requirements: {}

 

  ldap_cacert_secret: awx-custom-certs


This is my file kustomization.yaml

---

apiVersion: [kustomize.config.k8s.io/v1beta1](http://kustomize.config.k8s.io/v1beta1)

kind: Kustomization

namespace: awx

 

generatorOptions:

  disableNameSuffixHash: true

 

secretGenerator:

  - name: awx-secret-tls

    type: [kubernetes.io/tls](http://kubernetes.io/tls)

    files:

      - tls.crt

      - tls.key

 

  - name: awx-custom-certs

    type: Opaque

    files:

      - ldap-ca.crt=nkbm-ca2-intermediate.crt

 

  - name: awx-postgres-configuration

    type: Opaque

    literals:

      - host=awx-postgres-13

      - port=5432

      - database=awx

      - username=awx

      - password=Ansible123!

      - type=managed

 

  - name: awx-admin-password

    type: Opaque

    literals:

      - password=Ansible123!

 

  # If you want to specify SECRET_KEY for your AWX manually, uncomment following lines and change the value.

  # Refer AAC documentation for detail about SECRET_KEY.

  # https://docs.ansible.com/automation-controller/latest/html/administration/secret_handling.html

  #- name: awx-secret-key

  #  type: Opaque

  #  literals:

  #    - secret_key=MySuperSecureSecretKey123!

 

resources:

  - pv.yaml

  - pvc.yaml

  - awx.yaml




**IMPORTANT:**
Since it still didn't work for me, I decided to include a function where ldaps doesn't check the certificate and I'm just curious how in the container, for example, awx-648954959b-x69tm I change this configuration (/etc/tower/conf.d/ldap.py)

 AUTH_LDAP_GLOBAL_OPTIONS = {

    ldap.OPT_X_TLS_REQUIRE_CERT: True,

    ldap.OPT_X_TLS_CACERTFILE: "/etc/openldap/certs/ldap-ca.crt"

This ldap.OPT_X_TLS_REQUIRE_CERT: True  
I would like to change from True to False
I hope I was precise enough

**Comment by kurokobo** [comment]
@chiwuz 
Thanks for providing detailed information, this is super helpful for me to understand your situation. I've edited your comment above to make it easy to read by markdown syntax (just added code blocks for your YAML file).

> 2023-02-17 18:28:48,406 WARNING [3ad53c0ccde1439bbd2ec32f7d81f007] django_auth_ldap Caught LDAPError while authenticating SIKO1997: SERVER_DOWN({'result': -1, 'desc': "Can't contact LDAP server", 'ctrls': [], 'info': 'error:0A000086:SSL routines::certificate verify failed (unable to get issuer certificate)'})

This error usually indicates that the certification chain for your LDAP server can not be verified. You should ensure your `ldap-ca.crt` is PEM format and includes required chain.
I see your cert file is named `nkbm-ca2-intermediate.crt` so I guess this is intermediate CA certificate file. If so, please ensure that this file contains both intermediate CA cert and root CA cert.

Could you dig into the `awx-web` container and make further investigation?

```bash
# Get Bash shell of the `awx-web` container
$ kubectl -n awx exec -it deployment/awx -c awx-web -- bash
bash-5.1$      👈 Now you are in the awx-web container

# Ensure CA cert is mounted.
# The secret ldap_cacert_secret is mounted as /etc/openldap/certs/ldap-ca.crt
# This file should contain both intermediate CA cert and root CA cert, if your server cert is signed by intermediate CA
bash-5.1$ cat /etc/openldap/certs/ldap-ca.crt

# Ensure your CA cert has PEM format.
bash-5.1$ openssl x509 -in /etc/openldap/certs/ldap-ca.crt -text

# Test SSL connection to your LDAPS server using /etc/openldap/certs/ldap-ca.crt
# Press CTRL+C to exit
bash-5.1$ openssl s_client -connect <FQDN OF YOUR LDAP SERVER>:636 -no-CAfile -CAfile /etc/openldap/certs/ldap-ca.crt
```

This is example output on my lab (I've deployed lab for this issue😃).

```bash
# Contains two certs; one for intermediate CA, one for root CA
bash-5.1$ cat /etc/openldap/certs/ldap-ca.crt
-----BEGIN CERTIFICATE-----
MIIDizCCAnOgAwIBAgIUftINZYmeHvcovY0qBHp+SqZWrlswDQYJKoZIhvcNAQEL
...
3Eyhv0l7mJw/86twDMFFax+cKOCRFV6NoPOpzK1mzAXmxth6vk8DeRm0ipVpQVQ=
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIDizCCAnOgAwIBAgIUftINZYmeHvcovY0qBHp+SqZWrlwwDQYJKoZIhvcNAQEL
...
lVsDxZfbZVpRGkDr8odNurNmz0Xcttr+ZVRkoTy5KUxqIZhQuS6ySJj7yoLawWY=
-----END CERTIFICATE-----
```

```bash
# Certificate chain for my ldap.example.com has successfully verified
bash-5.1$ openssl s_client -connect ldap.example.com:636 -no-CAfile -CAfile /etc/openldap/certs/ldap-ca.crt
CONNECTED(00000003)
depth=2 C = JP, ST = Example State, O = EXAMPLE.COM, CN = rca.example.com      👈👈👈 Root
verify return:1
depth=1 C = JP, ST = Example State, O = EXAMPLE.COM, CN = ica.example.com      👈👈👈 Intermediate
verify return:1
depth=0 C = JP, ST = Example State, O = EXAMPLE.COM, CN = ldap.example.com      👈👈👈 Server
verify return:1
---
Certificate chain
 0 s:C = JP, ST = Example State, O = EXAMPLE.COM, CN = ldap.example.com      👈👈👈 Server
   i:C = JP, ST = Example State, O = EXAMPLE.COM, CN = ica.example.com
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Feb 18 05:56:56 2023 GMT; NotAfter: Feb 15 05:56:56 2033 GMT
 1 s:C = JP, ST = Example State, O = EXAMPLE.COM, CN = ica.example.com      👈👈👈 Intermediate
   i:C = JP, ST = Example State, O = EXAMPLE.COM, CN = rca.example.com
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Feb 18 05:31:55 2023 GMT; NotAfter: Feb 18 05:31:55 2024 GMT
 2 s:C = JP, ST = Example State, O = EXAMPLE.COM, CN = rca.example.com      👈👈👈 Root
   i:C = JP, ST = Example State, O = EXAMPLE.COM, CN = rca.example.com
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Feb 18 05:31:16 2023 GMT; NotAfter: Feb 15 05:31:16 2033 GMT
---
...
---
SSL handshake has read 3210 bytes and written 413 bytes
Verification: OK
...
SSL-Session:
    ...
    Verify return code: 0 (ok)
...
```

My comment on past issue (https://github.com/kurokobo/awx-on-k3s/issues/90#issuecomment-1156429862) is also helpful for you.

Alternatively, not tested yet but I think you can edit `/etc/tower/conf.d/ldap.py` in `awx-web` pod. This is a bit complicated way but my comment on past issue (https://github.com/kurokobo/awx-on-k3s/issues/90#issuecomment-1157745447) provides step-by-step instruction to edit specific file on the container. My comment is for `/etc/openldap/ldap.conf` but you can do the same way for `/etc/tower/conf.d/ldap.py`.

**Comment by chiwuz** [comment]
Thank you very much for your efforts, both for a good guide for setting up ansible on awx, and now for fixing this problem. I'm letting you know that I was able to fix the problem with your help. The problem was that I didn't have both chains in the certificate. When I added from ROOT, the thing started working.


Keep up the good work!!
