### ISSUE TITLE
How to customize welcome text and  logo on awx operator 1.1.4

### ISSUE THREAD

**Issue by chaitanya486** [kurokobo/awx-on-k3s#189]
## Environment

- OS: CentOS 8
- Kubernetes/K3s: k3s
- AWX Operator: 1.1.4
## Description
We want to update the welcome page text and change the logo from assets.
Could you please guide us how to do that

**Comment by kurokobo** [comment]
@chaitanya486 
Have you tried `Custom Logo` and `Custom Login Info` on `Settings` > `User Interface`? If these settings can not satisfy your requirements, please provide your goal in detail.

**Comment by chaitanya486** [comment]
Thanks for your email

We wanted to change the welcome text which are coming on login page like “
welcome to awx” . Also wanted to change the awx logo which is present in
header after login page.

As you mentioned those setting we tried but that can change only the front
page logo.

I hope this clears the things i wanted to update.


Regards,
Chaitanya Patil

**Comment by kurokobo** [comment]
@chaitanya486 
Thanks for updating, I understand your requirements.

Sadly there is no standard (smart) way to customize these strings and logos, but we can do it with a bit hacky way.

### Restrictions

- For login screen strings, allowed pattern is `Welcome to <BRAND_NAME>`. "Welcome to" can not be modified.
- For custom header images, only SVG is allowed.

### Prepare required files

- `default.strings.json`
  ```json
  {
      "BRAND_NAME": "Awesome Automation Platform",     👈👈👈 Will be embedded as `Welcome to <BRAND_NAME>`
      "PENDO_API_KEY": ""
  }
  ```
- `logo-header.svg`
  - The header image on AWX's Web UI
  - Example: <https://github.com/ansible/awx/blob/devel/awx/ui/public/static/media/logo-header.svg>
- `logo-login.svg`
  - The default large image on the login screen
  - Can be overridden by `Custom Logo` settings as my comment above
  - Example: <https://github.com/ansible/awx/blob/devel/awx/ui/public/static/media/logo-login.svg>

### Create ConfigMap

```bash
$ kubectl -n awx create configmap awx-custom-files \
  --from-file=default.strings.json \
  --from-file=logo-header.svg \
  --from-file=logo-login.svg
```

### Modify your `base/awx.yaml`

Append `extra_volumes` and `web_extra_volume_mounts`.

```bash
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  ...
  extra_volumes: |
    - name: awx-custom-files
      configMap:
        name: awx-custom-files
  web_extra_volume_mounts: |
    - name: awx-custom-files
      mountPath: /var/lib/awx/public/static/media/logo-header.svg
      subPath: logo-header.svg
    - name: awx-custom-files
      mountPath: /var/lib/awx/public/static/media/logo-login.svg
      subPath: logo-login.svg
    - name: awx-custom-files
      mountPath: /var/lib/awx/public/static/media/default.strings.json
      subPath: default.strings.json
```

### Apply it

Apply it and wait for complete.

```bash
kubectl apply -k base
```

### Result

![image](https://user-images.githubusercontent.com/2920259/224112947-e3ccb5f1-886d-4ddc-b1be-efaf2385ceb7.png)
![image](https://user-images.githubusercontent.com/2920259/224113011-5db87a1b-b3f4-47fc-9244-fa849a6415eb.png)

### Additional Info

If you are familiar with building container image, it is also possible to create an image that replaces the above set of files and specify it in CR (`image` and `image_version`).
