### ISSUE TITLE
ubuntu 22.04 kvm k3s and awx 1.3.0 operator not working

### ISSUE THREAD

**Issue by bobby0724** [kurokobo/awx-on-k3s#191]
I have follow your guide step by step on a ubuntu 22.04 virtual machine but the awx por is failing i check the logs and is just crahisng do you know what can be ?

NAME                                                   READY   STATUS                  RESTARTS      AGE
pod/awx-operator-controller-manager-68d6f576b4-28psv   2/2     Running                 0             14m
pod/awx-postgres-13-0                                  1/1     Running                 0             11m
pod/awx-6d5dff6db7-n2vsj                               0/4     Init:CrashLoopBackOff   5 (84s ago)   4m23s

NAME                                                      TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
service/awx-operator-controller-manager-metrics-service   ClusterIP   10.43.8.235    <none>        8443/TCP   14m
service/awx-postgres-13                                   ClusterIP   None           <none>        5432/TCP   11m
service/awx-service                                       ClusterIP   10.43.31.109   <none>        80/TCP     10m

NAME                                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/awx-operator-controller-manager   1/1     1            1           14m
deployment.apps/awx                               0/1     1            0           10m

NAME                                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/awx-operator-controller-manager-68d6f576b4   1         1         1       14m
replicaset.apps/awx-6d5dff6db7                               1         1         0       10m

NAME                               READY   AGE
statefulset.apps/awx-postgres-13   1/1     11m

**Comment by kurokobo** [comment]
@bobby0724 
Please do not omit issue template... That template helps me to understand your situation corectly.

Anyway the error `Init:CrashLoopBackOff` means that your init container exxtited with error.
You can gather logs from init containers (`init` and `init-projects`) by;

```bash
$ kubectl -n awx logs deployment/awx -c init
$ kubectl -n awx logs deployment/awx -c init-projects
```

**Comment by bobby0724** [comment]
thanks i found the issue, the vm is missing some cpu instructions, i need to create it with passthru
