### ISSUE TITLE
Getting issue while running ansible playboo

### ISSUE THREAD

**Issue by chaitanya486** [kurokobo/awx-on-k3s#192]
## Environment

- OS: CentOS 8
- Kubernetes/K3s: k3s
- AWX Operator: 1.1.4

## Description
We are getting below error while executing playbook. We have working same playbook before. after upgrade it is giving below error.
Could you please help us

No config file found; using defaults
SSH password: 
ERROR! couldn't resolve module/action 'win_lineinfile'. This often indicates a misspelling, missing collection, or incorrect module path.
The error appears to be in '/runner/project/Env_setup_PNC.yml': line 59, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

**Comment by kurokobo** [comment]
@chaitanya486 
First of all, ensure your EE image contains `community.windows` module or you have `requirements.yml` that specifies `community.windows` in your project.

**Comment by kurokobo** [comment]
See my troubleshooting guide for this topic: https://github.com/kurokobo/awx-on-k3s/blob/main/tips/troubleshooting.md#the-job-failed-and-i-got-error-couldnt-resolve-moduleaction-or-failed-to-import-the-required-python-library-message

**Comment by chaitanya486** [comment]
Getting this error , i followed below steps.

vi builder/requirements.yml

---
collections:
  - name: community.general
    version: 6.0.0
    source: https://galaxy.ansible.com
  - name: ansible.windows
    version: 1.13.0
  # see https://galaxy.ansible.com/chocolatey/chocolatey
  - name: chocolatey.chocolatey
    version: 1.4.0
  # see https://galaxy.ansible.com/community/general
  - name: community.general
    version: 6.4.0
  # see https://galaxy.ansible.com/community/windows
  - name: community.windows
    version: 1.12.0



ansible-builder build --tag registry.example.com/ansible/ee:2.12-custom --container-runtime docker --verbosity 3

ValueError: unknown action "extend"




ansible-builder build --tag registry.example.com/ansible/ee:2.12-custom --container-runtime docker --verbosity 3
ValueError: unknown action "extend"

**Comment by chaitanya486** [comment]
Could you please provide exact steps so that we can apply it for community.windows. we have already setup awx 1.1.4.

**Comment by chaitanya486** [comment]
i tried all the steps mentioned in the URL but execution environment is created new as CUSTOM-EE .
Is there any possibility to update the EE in existing AWX-EE execution environment.

**Comment by kurokobo** [comment]
@chaitanya486 

> Could you please provide exact steps

My guide provides exact steps. Use Python 3.8 or later to avoid your error about `extend` action.

> Is there any possibility to update the EE in existing AWX-EE execution environment.

If your project type is NOT "Manual", you can use additional collections without building custom EE by placing `collections/requirements.yml on your project root. The guide also contains description for this method. See [Use Ansible collections without custom EE](https://github.com/kurokobo/awx-on-k3s/tree/main/builder#use-ansible-collections-without-custom-ee) section.

**Comment by chaitanya486** [comment]
Ok thanks this helps. But in this case does it will install while every project sync up.

**Comment by kurokobo** [comment]
@chaitanya486 

> But in this case does it will install while every project sync up.

Yes, installing collections using `requirements.yml` is a part of project update. See this playbook that internally used for project update: https://github.com/ansible/awx/blob/devel/awx/playbooks/project_update.yml#L232-L251

**Comment by kurokobo** [comment]
Closing this since this seems to be solved. Please feel free to open new issue if you have any further questions.
