### ISSUE TITLE
Cannot deploy when task_extra_env is specified

### ISSUE THREAD

**Issue by vrubiolo** [kurokobo/awx-on-k3s#20]
Hi again, and thanks for keeping this great project updated!

I am hitting an issue today so I am opening up a report here as I cannot manage to use `task_extra_env` to set `AWX_CLEANUP_PATHS` to `False` (this is related to https://groups.google.com/g/awx-project/c/XhY-uDSxDIo/m/CnhjRQG5AAAJ).

I have double-checked but let me know if I oversaw something. I am filing here since I deploy via your repo but this may be an issue with the upstream operator.

## Environment
- K3S: `k3s version v1.19.15+k3s1 (e698d6d8)`
- OS: Ubuntu 20.04.3 LTS
- AWX Operator: 0.14.0

## Description
When `task_extra_env` is set to the following, the operator cannot deploy via the updated CRD:
```
 task_extra_env: |
    - name: AWX_CLEANUP_PATHS
      value: false
```

The syntax I used is in line with what is advised at https://github.com/ansible/awx-operator#exporting-environment-variables-to-containers:
```
  spec:
    task_extra_env: |
      - name: MYCUSTOMVAR
        value: foo
    web_extra_env: |
      - name: MYCUSTOMVAR
        value: foo
    ee_extra_env: |
      - name: MYCUSTOMVAR
        value: foo
```

Yet the deployment fails:
```
TASK [installer : Apply deployment resources] **********************************\r\ntask path: /opt/ansible/roles/installer/tasks/resources_configuration.yml:35\nfatal: [localhost]: FAILED! => {\"changed\": false, \"error\": 400, \"msg\": \"Failed to apply object: b'{\\\"kind\\\":\\\"Status\\\",\\\"apiVersion\\\":\\\"v1\\\",\\\"metadata\\\":{},\\\"status\\\":\\\"Failure\\\",\\\"message\\\":\\\"Deployment in version \\\\\\\\\\\"v1\\\\\\\\\\\" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects \\\\\\\\\\\" or n, but found f, error found in #10 byte of ...|,\\\\\\\\\\\"value\\\\\\\\\\\":false}],\\\\\\\\\\\"im|..., bigger context ...|amespace\\\\\\\\\\\"}}},{\\\\\\\\\\\"name\\\\\\\\\\\":\\\\\\\\\\\"AWX_CLEANUP_PATHS\\\\\\\\\\\",\\\\\\\\\\\"value\\\\\\\\\\\":false}],
```

I can indeed see the CRD looks fishy. Note the bizarre whitespace placement, indentation was lost. Full output is attached:
```
$ kubectl describe awx
[...]
  Replicas:                         1
  route_tls_termination_mechanism:  Edge
  task_extra_env:                   - name: AWX_CLEANUP_PATHS
  value: false

  task_privileged:  false
Status:
  Conditions:
    Last Transition Time:  2021-12-07T14:03:53Z
```

I suspect this is because the templating might be too simple at https://github.com/ansible/awx-operator/blob/devel/roles/installer/templates/deployment.yaml.j2#L266 and not take into account the more complex data structure but I might be wrong.

Did you successfully manage to override those environment variables this way?

## Step to Reproduce

1. Deploy AWX as per your instructions but stop to modify `base/awx.yaml` to use the attached one
2. Perform a `kubectl apply -k base/` as usual
3. Notice how the deployment fails at the operator level, with the abovementioned error.

Logs + full `base/` directory: [extra_env_error.zip](https://github.com/kurokobo/awx-on-k3s/files/7668981/extra_env_error.zip)

**Comment by kurokobo** [comment]
Add double-quote to `false`.

```yaml
  task_extra_env: |
    - name: AWX_CLEANUP_PATHS
      value: "false"
```

`false` (or `true`) without quote will be treated as **Bool** type, but the `value` under `env` have to be **String** type. Therefore quoting is required in your case.

**Comment by kurokobo** [comment]
Works good for me with double-quoted `"false"`:

```bash
[kuro@kuro-awx01 tmp]$ kubectl -n awx-vincent describe deployment awx
...
   awx-task:
    ...
    Environment:
      ...
      MY_POD_IP:                    (v1:status.podIP)
      MY_POD_NAMESPACE:             (v1:metadata.namespace)
      AWX_CLEANUP_PATHS:           false
```

**Comment by kurokobo** [comment]
Am I correct in understanding that the AWX deployment completes, but running a job in that AWX results in an error?

If so, it seems the issue related with `SECRET_KEY` which is used by AWX to encrypt/decrypt credentials in DB.
`SECRET_KEY` was automatically generated by AWX Operator during initial deployment and stored as a `Secret` resource (`awx-secret-key`) in the namespace you specified in your K8s cluster.

So, sadly, the `SECRET_KEY` which required to decrypt the data in your DB has been lost by `kubectl delete -k base/` I think. The command `kubectl delete -k base/` delete whole namespace, this means your `Secret` was also deleted.

Your possible choices in my understanding are:

1. Create new credentials in AWX and use new one from Job Template, instead of overwriting existing credentials.
2. If you don't want to lose your data and you have a backup of AWX instance, since `SECRET_KEY` is included in it, you can create `awx-secret-key` manually first by referring to the following document and then redeploy instance: <https://github.com/ansible/awx-operator/blob/devel/docs/migration.md#secret-key>
3. If you don't mind losing all your data, delete and redeploy everything, including the persisted data under `/data`

**Comment by vrubiolo** [comment]
Hi again @kurokobo  and thanks for the super fast assistance, again :bowing_man: 

> Am I correct in understanding that the AWX deployment completes, but running a job in that AWX results in an error?

Yes, that is correct. The job will fail whatever the situation here, even if I delete everything via `kubectl delete -k base/` and redeploy again.

> 
> If so, it seems the issue related with `SECRET_KEY` which is used by AWX to encrypt/decrypt credentials in DB. `SECRET_KEY` was automatically generated by AWX Operator during initial deployment and stored as a `Secret` resource (`awx-secret-key`) in the namespace you specified in your K8s cluster.
> 
> So, sadly, the `SECRET_KEY` which required to decrypt the data in your DB has been lost by `kubectl delete -k base/` I think. The command `kubectl delete -k base/` delete whole namespace, this means your `Secret` was also deleted.

Good analysis, I had not realized what the `SECRET_KEY` part meant/was used.

I indeed witnessed the namespace being deleted as well with `kubectl delete -k base/` but what is strange here is that such deletion and redeployment worked multiple times before. In other words, I could use `kubectl delete -k base/` and redo a `kubectl apply -k base/` and get my data back (as you had hinted at https://github.com/kurokobo/awx-on-k3s/issues/10#issuecomment-940975667). Would that mean the credentials part in the DB is not included in this i.e even though the instance comes back up after `kubectl delete -k base/` +  `kubectl apply -k base/` (with the same kustomization files), the data is actually unusable because of the lost secret?

> 
> Your possible choices in my understanding are:
> 
>     1. Create new credentials in AWX and use new one from Job Template, instead of overwriting existing credentials.

I see. I will try that. This would explain how I managed to get a successful run w/ a different credential. Fortunately only the credentials are encrypted, not the rest of the data :relieved: 

> 
>     2. If you don't want to lose your data and you have a backup of AWX instance, since `SECRET_KEY` is included in it, you can create `awx-secret-key` manually first by referring to the following document and then redeploy instance: https://github.com/ansible/awx-operator/blob/devel/docs/migration.md#secret-key

Hahaha :smile: . Too late. I only started looking into the backup CRD after I wrote my post above (I do have backups of the full VM though if needed).

I could perform a backup today but I think this includes the new secret key, not the older one. Thanks again for your backup instructions btw, they are cristal clear compared to what is in the original project, you could very well contribute them upstream if you wanted.

> 
>     3. If you don't mind losing all your data, delete and redeploy everything, including the persisted data under `/data`

Yes, that is always the possibility indeed. I am also looking into the AWX Ansible collection as my goal is to be able to recreate all templates/projects/credentials if needed from a blank/throwable instance (to avoid these kind of issues).

**Comment by vrubiolo** [comment]
Hi @kurokobo,

Thank you again for the detailed explanation and the pointer to the Ansible Tower docs  + the additional explanation about secret management on K8S, this was very helpful for me to understand those internals! 

I do read the Tower/Automation Controller docs when I need information on a particular topic but did not browse this section.

I can also confirm that reusing the database by redeploying everything AND recreating the secrets manually allowed the jobs to resume/work properly. Feel thus free to close this ticket.

Again, big thanks for your assistance!

**Comment by kurokobo** [comment]
Thanks for updating! Good to hear that, will close this issue :)
