### ISSUE TITLE
pod/awx-task not initiating

### ISSUE THREAD

**Issue by jeromearellano** [kurokobo/awx-on-k3s#202]
[log.txt](https://github.com/kurokobo/awx-on-k3s/files/11168848/log.txt)
Hello, it's my first time reporting an issue i experienced while installing Ansible AWX.
Hopefully these data is helpful for your investigation.

## Environment
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3+k3s1", GitCommit:"01ea3ff27be0b04f945179171cec5a8e11a14f7b", GitTreeState:"clean", BuildDate:"2023-03-27T22:23:17Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3+k3s1", GitCommit:"01ea3ff27be0b04f945179171cec5a8e11a14f7b", GitTreeState:"clean", BuildDate:"2023-03-27T22:23:17Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}

- OS: CentOS Stream 9
- Kubernetes/K3s: 1.26.3
- AWX Operator: 2.0.0

## Description
I'm new to ansibe and I want to test the latest release however for some reason the pod/awx-task is not initiating.
![image](https://user-images.githubusercontent.com/75210283/230334766-11c5c278-49fb-4d96-b6ea-4b1338102327.png)

## Logs
Snippet of the log below. The whole log is attached.
```
......
{"level":"error","ts":1680771544.5242317,"logger":"logging_event_handler","msg":"","name":"awx","namespace":"awx","gvk":"awx.ansible.com/v1beta1, Kind=AWX","event_type":"runner_on_failed","job":"3532316322307741009","EventData.Task":"Apply deployment resources","EventData.TaskArgs":"","EventData.FailedTaskPath":"/opt/ansible/roles/installer/tasks/resources_configuration.yml:248","error":"[playbook task failed]","stacktrace":"github.com/operator-framework/operator-sdk/internal/ansible/events.loggingEventHandler.Handle
\t/workspace/internal/ansi
[log.txt](https://github.com/kurokobo/awx-on-k3s/files/11168829/log.txt)
ble/events/log_events.go:111"}

{"level":"error","ts":1680771544.6979263,"logger":"runner","msg":"ansible-playbook 2.9.27\r
  config file = /etc/ansible/ansible.cfg\r
  configured module search path = ['/usr/share/ansible/openshift']\r
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible\r
  executable location = /usr/local/bin/ansible-playbook\r
  python version = 3.8.13 (default, Jun 14 2022, 17:49:07) [GCC 8.5.0 20210514 (Red Hat 8.5.0-13)]\r
  Using /etc/ansible/ansible.cfg as config file\r
  Skipping callback 'actionable', as we already have a stdout callback.
  Skipping callback 'awx_display', as we already have a stdout callback.
  Skipping callback 'counter_enabled', as we already have a stdout callback.
  Skipping callback 'debug', as we already have a stdout callback.
  Skipping callback 'dense', as we already have a stdout callback.
  Skipping callback 'dense', as we already have a stdout callback.
  Skipping callback 'full_skip', as we already have a stdout callback.
  Skipping callback 'json', as we already have a stdout callback.
  Skipping callback 'minimal', as we already have a stdout callback.
  Skipping callback 'null', as we already have a stdout callback.
  Skipping callback 'oneline', as we already have a stdout callback.
  Skipping callback 'selective', as we already have a stdout callback.
  Skipping callback 'skippy', as we already have a stdout callback.
  Skipping callback 'stderr', as we already have a stdout callback.
  Skipping callback 'unixy', as we already have a stdout callback.
  Skipping callback 'yaml', as we already have a stdout callback.
.....
PLAY RECAP *********************************************************************
localhost                  : ok=62   changed=0    unreachable=0    failed=1    skipped=64   rescued=0    ignored=0   
","job":"3532316322307741009","name":"awx","namespace":"awx","error":"exit status 2","stacktrace":"github.com/operator-framework/operator-sdk/internal/ansible/runner.(*runner).Run.func1
   /workspace/internal/ansible/runner/runner.go:269"}

----- Ansible Task Status Event StdOut (awx.ansible.com/v1beta1, Kind=AWX, awx/awx) -----


PLAY RECAP *********************************************************************
localhost                  : ok=62   changed=0    unreachable=0    failed=1    skipped=64   rescued=0    ignored=0
```

## Step to Reproduce
I followed your guide in installing [AWX on Single Node K3s](https://github.com/kurokobo/awx-on-k3s)
1. disabled firewalld
2. Install K3s
3. Install AWX Operator version 2.0.0
4. Prepared the required files for AWX
5. Deploy AWX using `kubectl apply -k base`

**Comment by kurokobo** [comment]
@jeromearellano 
Thanks for reporting and sorry for this, my bad. `awx.yaml` in this repo contained incorrect settings 😢
I was using the wrong file when I did the test to update guide.

I've fixed this now, so please try again with updated `awx.yaml`: https://github.com/kurokobo/awx-on-k3s/blob/main/base/awx.yaml

The log file you provided helps me a lot! Thanks again for providing detailed information with the issue. It contains following error that indicates there was a conflict for the volume name:

> "msg\": \"Failed to apply object: b'{\\\"kind\\\":\\\"Status\\\",\\\"apiVersion\\\":\\\"v1\\\",\\\"metadata\\\":{},\\\"status\\\":\\\"Failure\\\",\\\"message\\\":\\\"Deployment.apps \\\\\\\\\\\"awx-task\\\\\\\\\\\" is invalid: spec.template.spec.volumes[15].name: Duplicate value: \\\\\\\\\\\"awx-projects\\\\\\\\\\\"

**Comment by sealclubber** [comment]
Had this exact problem earlier and OP opened the ticket before I could. Just updated, reran everything and it works like a charm. Thanks to both you guys.

**Comment by jeromearellano** [comment]
@kurokobo Thank you for the immediate attention and time to debug. I re-deployed and it works!
