### ISSUE TITLE
Issue when building the custom EE environnement

### ISSUE THREAD

**Issue by mehdia4ever** [kurokobo/awx-on-k3s#204]
## Environment ##

- OS: Ubuntu 20.04.6 LTS
- Ansible-builder:  1.2.0
- Docker-version: 20.10.21

## Description ##

Issue when building custom EE environnement.

Am having a issue when i am running my command to build a custom EE using your files in the builder repository.

## Command ##

ansible-builder build --tag quay.io/my-repo/ee:1.0-custom --container-runtime docker --verbosity 3

## Logs ##

 ---> Running in e87e0b4989c6
Starting galaxy collection install process
Process install dependency map
[WARNING]: Skipping Galaxy server https://galaxy.ansible.com. Got an unexpected
error when getting available versions of collection community.general: Unknown
error when attempting to call Galaxy at 'https://galaxy.ansible.com/api/':
<urlopen error [Errno 99] Cannot assign requested address>
ERROR! Unknown error when attempting to call Galaxy at 'https://galaxy.ansible.com/api/': <urlopen error [Errno 99] Cannot assign requested address>
The command '/bin/sh -c ANSIBLE_GALAXY_DISABLE_GPG_VERIFY=1 ansible-galaxy collection install $ANSIBLE_GALAXY_CLI_COLLECTION_OPTS -r requirements.yml --collections-path "/usr/share/ansible/collections"' returned a non-zero code: 1

An error occured (rc=1), see output line(s) above for details.

Have you any ideas about this error ?

Thank's in advance

**Comment by kurokobo** [comment]
Hmm never seem that error and can't be reproduced on my side.
Could you please dig into Docker container?

```bash
# Run these commands on your Docker host
$ docker version
$ docker run --rm -it --entrypoint /bin/bash quay.io/ansible/ansible-runner:stable-2.12-latest

# Then run these commands in the container
bash-4.4# curl https://galaxy.ansible.com/
bash-4.4# ansible-galaxy collection install community.general
```

**Comment by mehdia4ever** [comment]
I forget to tell am running this command behind a corporate proxy.

docker version
Client:
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.1
 Git commit:        20.10.21-0ubuntu1~20.04.1
 Built:             Thu Jan 26 21:14:47 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.1
  Git commit:       20.10.21-0ubuntu1~20.04.1
  Built:            Thu Nov 17 20:19:30 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.12-0ubuntu1~20.04.1
  GitCommit:
 runc:
  Version:          1.1.4-0ubuntu1~20.04.1
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:

root@XXX# docker run --rm -it --entrypoint /bin/bash quay.io/ansible/ansible-runner:stable-2.12-latest

bash-4.4# curl https://galaxy.ansible.com/
^C
bash-4.4# ansible-galaxy collection install community.general
Starting galaxy collection install process
Process install dependency map
[WARNING]: Skipping Galaxy server https://galaxy.ansible.com. Got an unexpected error when getting available versions of collection community.general: Unknown error when attempting to call Galaxy at 'https://galaxy.ansible.com/api/':
<urlopen error [Errno 99] Cannot assign requested address>
ERROR! Unknown error when attempting to call Galaxy at 'https://galaxy.ansible.com/api/': <urlopen error [Errno 99] Cannot assign requested address>

**Comment by kurokobo** [comment]
> I forget to tell you that am running this command behind a corporate proxy.

Ah so you should configure Docker to use proxy: https://docs.docker.com/network/proxy/
Or append following configuration to your `execution-environment.yml`:

```yaml
additional_build_steps:
  prepend:
    - ENV http_proxy proxy.example.com
    - ENV https_proxy proxy.example.com
    - ENV HTTP_PROXY proxy.example.com
    - ENV HTTPS_PROXY proxy.example.com
```
