### ISSUE TITLE
The node was low on resource: ephemeral-storage

### ISSUE THREAD

**Issue by Nilesh486** [kurokobo/awx-on-k3s#205]
## Environment

- OS: CentOS 8
- Kubernetes/K3s: K3s
- AWX Operator: 1.1.4

## Description

We are getting multiple failures due to below Issue . POD is getting terminated intermittently.
Following error shows up while we describe POD, Can we get the solution for it. how to assign or increase temporary storage.
Can someone guide on it.

Name:             awx-75cb6698f9-c9swp
Namespace:        awx
Priority:         0
Service Account:  awx
Node:             *************************************
Start Time:       Thu, 23 Mar 2023 17:56:25 +0530
Labels:           app.kubernetes.io/component=awx
                  app.kubernetes.io/managed-by=awx-operator
                  app.kubernetes.io/name=awx
                  app.kubernetes.io/operator-version=1.1.4
                  app.kubernetes.io/part-of=awx
                  app.kubernetes.io/version=21.11.0
                  pod-template-hash=75cb6698f9
Annotations:      <none>
Status:           Failed
Reason:           Evicted
Message:          The node was low on resource: ephemeral-storage. Container awx-ee was using 195868Ki, which exceeds its request of 0. Container awx-web was using 21208Ki, which exceeds its request of 0. Container awx-task was using 68236Ki, which exceeds its request of 0. Container redis was using 2432Ki, which exceeds its request of 0.
IP:               **********

Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  awx-application-credentials:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  awx-app-credentials
    Optional:    false
  awx-receptor-tls:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  awx-receptor-ca:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  awx-receptor-ca
    Optional:    false
  awx-receptor-work-signing:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  awx-receptor-work-signing
    Optional:    false
  awx-secret-key:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  awx-secret-key
    Optional:    false
  awx-settings:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      awx-awx-configmap
    Optional:  false
  awx-nginx-conf:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      awx-awx-configmap
    Optional:  false
  awx-redis-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      awx-awx-configmap
    Optional:  false
  awx-redis-socket:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  awx-redis-data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  supervisor-socket:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  rsyslog-socket:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  receptor-socket:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  rsyslog-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  awx-receptor-config:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  awx-default-receptor-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      awx-awx-configmap
    Optional:  false
  awx-projects:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  awx-projects-claim
    ReadOnly:   false
  awx-custom-files:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      awx-custom-files
    Optional:  false
  kube-api-access-rtq2g:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>

...
```

**Comment by kurokobo** [comment]
@Nilesh486 
K3s consumes disk space under `/var/lib/rancher` for containers' file system. Ensure your `/var/lib/rancher` has enough free space.

**Comment by Nilesh486** [comment]
Thankyou this helps

**Comment by Nilesh486** [comment]
Does it possible to use clean up for this consumption.
i found below solution over multiple blogs, is it reliable to use it for our k3s setup to clean up old images, does it free the space for /var/lib/rancher this path. We have custom EE and instance group.
sudo k3s crictl images to see what images have been pulled locally
sudo k3s crictl rmi --prune to delete any images no currently used by a running container

**Comment by kurokobo** [comment]
It's safe to run `sudo k3s crictl rmi --prune` on your k3s, but it depends on your usage that your disk (`/var/lib/rancher`) will be freed up or not.
That command removes only unused images so if there are no unused images on your k3s no space will be freed up.

**Comment by Nilesh486** [comment]
Thankyou  for clarification
