### ISSUE TITLE
White blank page after deploy

### ISSUE THREAD

**Issue by halobolah** [kurokobo/awx-on-k3s#206]
Hi,

first of all - great Tutorial :)

After deployment I can't access to web gui, I have only white blank page. What should I check ? 
![image](https://user-images.githubusercontent.com/28426539/232824564-54f80fec-df2a-40aa-a8c0-3f6db8d90984.png)

on system everything looks ok:
![image](https://user-images.githubusercontent.com/28426539/232824857-eec1fb48-1a8d-4d28-bff5-06a5c3994210.png)

What am I missing ? :) thanks for your help

**Comment by kurokobo** [comment]
@halobolah 
Try this: https://github.com/ansible/awx/issues/13756#issuecomment-1488786986
