### ISSUE TITLE
Custom CA Certificate Chain is untrusted

### ISSUE THREAD

**Issue by namoyer10** [kurokobo/awx-on-k3s#209]
First, thank you for setting all of this up and creating the detailed documentation for this project. I have just started playing around with k8s and k3s and have began looking into incorporating AWX inside my home lab for testing and potential use. I currently have a Foreman instance stood up and would like to use it as an inventory source. I have created the credential and inventory but continually receive self signed certificate verification errors. 
```
[WARNING]:  * Failed to parse /runner/inventory/foreman.yml with auto plugin:
HTTPSConnectionPool(host='foreman.<domain>.com', port=443): Max retries
exceeded with url: /api/v2/status?page=1&per_page=250 (Caused by
SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED]
certificate verify failed: self-signed certificate in certificate chain
(_ssl.c:1129)')))
```
I have added the CA bundle to the kustomization file:
```
  - name: awx-custom-certs
    type: Opaque
    files:
      - ldap-ca.crt=ldap.crt
      - bundle-ca.crt=bundle-ca.crt
```
I manually entered the awx-web, awx-task, and awx-ee pods and was able to successfully connect to the host over port 443 and TLS1.3 without certificate errors. Any idea on where to go for additional troubleshooting?

I have included both the intermediate and root CA in the bundle in the form of
```
-----BEGIN CERTIFICATE-----
<Intermediate CA>
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
<Root CA>
-----END CERTIFICATE-----
```
Connection:
```
kubectl -n awx exec -it deployment/awx-task -c awx-ee -- bash

openssl s_client -connect foreman.<domain>.com:443 -no-CAfile -CAfile /etc/pki/ca-trust/source/anchors/bundle-ca.crt
...
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 4096 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
...
```

I appreciate any help moving forward.

**Comment by kurokobo** [comment]
@namoyer10 
Hi, thanks for using my guide.

One thing you should to know is, the inventory sync is processed in the ephemeral automation job pod, as well as the job that launched from job template. The automation job pod is created on the start of the inventory sync, and is deleted once the sync is completed.
So, sadly, the certificates that mounted on `web`, `task`, and `ee` container _do nothing_ for inventory sync.

There are several solutions for this.

- A) Create custom EE image that includes your CA certs, and specify this EE as the EE for inventory sync.
- B) Configure cert store on your K3s host, and enable `Expose host paths for Container Groups` option in AWX.

The easiest way is choice B.

1. Place your CA cert (this file have to be PEM format) under `/etc/pki/ca-trust/source/anchors/` on your K3s host.
2. Invoke `sudo update-ca-trust` on your K3s host.
3. Enable `Expose host paths for Container Groups` option in `Settings` > `Job` on AWX.
4. Ensure `"/etc/pki/ca-trust:/etc/pki/ca-trust:O"` is included in `Paths to expose to isolated jobs` in `Settings` > `Job` on AWX (this is configured by default).

Now `/etc/pki/ca-trust` on your K3s host contains your CA cert, and this path will be mounted on all automation job pods.
Note that this configuration is global, so the same path will be mounted on the pods not only inventory sync but also the pods for standard jobs.

As a side note, I have a plan to add new guide about this topic (see #196).

**Comment by namoyer10** [comment]
@kurokobo thanks for the response!

I am still missing something but not sure what. I tried using both of your suggestions above with no luck.

For option A, I ended up just inserting my custiom CA bundle into the upstream container and saving it locally on my personal managed harbor server. The simple dockerfile looks like this:
```
FROM quay.io/ansible/awx-ee:latest

USER root
COPY ca-bundle.crt /etc/pki/ca-trust/source/anchors/ca-bundle.crt
RUN update-ca-trust
USER 1000
```
This image seems to work if I pull it locally but does not seem to work through the AWX inventory sync job. I set the execution environment to use this new container and can see the application pull from my harbor instance, but I still receive the SSL verification error.

For option B, I set the value mentioned above and verified that the `/etc/pki/ca-trust:/etc/pki/ca-trust:0` line is present in the `Paths to expose to isolated jobs`. Again, I still get the SSL verification error when attempting to sync the inventory. 

Am I missing something obvious? Thanks again for the help, truly appreciate it.

**Comment by kurokobo** [comment]
> This image seems to work if I pull it locally but does not seem to work through the AWX inventory sync job.

You shoud specify `Always pull container before running` as `Pull` on the `Edit` page of your Execution Environment, for testing purpose to force to re-pull your EE image from container registry.

**Comment by namoyer10** [comment]
@kurokobo it is very strange. Everything looks correct from what I can tell. Inspecting the running job automation pod has the correct trust certificates installed. I even ran a `curl` command from the AWX UI through the execution environment and received the expected output in the job logs. From what I can tell it is only the sync jobs that are having issues. I may have to throw in the towel on this one. I will do a little more snooping and see if the foreman inventory sync roll expects a CA certificate as a variable but I would expect it to use the underlying python trust store which in turn should use the system trust.

**Comment by kurokobo** [comment]
Hmm seems the issue has been reproduced on my side. Interesting. Will look into this.

**Comment by kurokobo** [comment]
@namoyer10 
TIL: `requests` does not use trusted cert store on the OS.

> Requests uses certificates from the package [certifi](https://certifiio.readthedocs.io/).
> ...
> This list of trusted CAs can also be specified through the `REQUESTS_CA_BUNDLE` environment variable. If `REQUESTS_CA_BUNDLE` is not set, `CURL_CA_BUNDLE` will be used as fallback.
> https://requests.readthedocs.io/en/latest/user/advanced/

My bad, I don't know this behavior. So, we should specify `REQUESTS_CA_BUNDLE` by some way, in addition to method A or B. The value of this env should be the full path of your ca bundle in the EE image, or `/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem` (or `/etc/ssl/cert.pem`, this is symlink for the `/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem`).

Try adding following variable into `Source variables` under `Edit` page of the `Source` of your inventory.

```yaml
---
REQUESTS_CA_BUNDLE: /etc/ssl/cert.pem
```

**Comment by namoyer10** [comment]
@kurokobo Great catch! I wasn't able to get it working by adding the `REQUESTS_CA_BUNDLE: /etc/ssl/cert.pem` to the `Source variables` section but I was able to add it as an environmental variable to the custom EE container I built (also changed the cert.pem path). The new dockerfile looks like so:
```
FROM quay.io/ansible/awx-ee:latest

USER root
COPY ca-bundle.crt /etc/pki/ca-trust/source/anchors/ca-bundle.crt
RUN update-ca-trust
ENV REQUESTS_CA_BUNDLE=/etc/pki/tls/cert.pem
USER 1000
```

I did notice that under `Settings` -> `Jobs settings` that there is a box for `Extra Environment Variables`. I will try and add the ENV variable there and run the default image. Will let you know, thanks for all the help!

**Comment by namoyer10** [comment]
Ok, just to be thorough, if you enable `Expose host paths for Container Groups` and add the request bundle to the `Extra Environment Variables` box:
```
{
  "REQUESTS_CA_BUNDLE": "/etc/pki/tls/cert.pem"
}
```
The default image from quay.io is able to successfully sync from a Custom CA.

**Comment by kurokobo** [comment]
Congrats, thanks for updating!

On my side, enabling `Expose host paths for Container Groups` and adding env to `Source variables` with default EE works well.

Have you tried adding `REQUESTS_CA_BUNDLE
: /etc/pki/tls/cert.pem` (updated pem path) into `Source variable` section, with `Expose host paths for Container Groups` enabled?

**Comment by namoyer10** [comment]
Gotcha, I did not try that combination. Only with the Expose disabled. I will probably continue with the custom EE container though. I would like to move all of the necessary containers to an internal source and remove external access from the k3s cluster in the future.

**Comment by Dustin-Wi** [comment]
Sorry to resurrect this old issue.  I'm following these instructions to get Playbook and Inventory Sync working for external services using an internally signed certificate.

https://github.com/kurokobo/awx-on-k3s/blob/main/tips/trust-custom-ca.md#method-2-mount-host-filesystem

Part of the recommended troubleshooting you mention above and in the instructions is to connect to the Job Pod to tshoot.  I added a 10 minute pause to my playbook and I can see the job pod getting created with "kubectl get pods -n awx".  However, I can't figure out the command to connect to the pod.

What command would I use to connect to the automation-job pod?
