### ISSUE TITLE
Include documentation for external PostgreSQL database

### ISSUE THREAD

**Issue by str8edgedave** [kurokobo/awx-on-k3s#21]
Thank-you for this awesome guide. I was able to get AWX working with minimal difficulties.

Would it be possible to get an alternate set of documentation that shows how to use an external (unmanaged) PostgreSQL database?

**Comment by kurokobo** [comment]
Good point, actually it's not so difficult to deploy with external (existing) DB.
The things to do is mainly modifying `awx-postgres-configuration` in `kustomize.yml` and `postgres_*` in `awx.yaml`.

Required params are described in the [`README.md` in awx-operator](https://github.com/ansible/awx-operator#external-postgresql-service), but I will consider adding some tips or hints to my guides. Thanks 😃

**Comment by kurokobo** [comment]
Added extra guide "[Deploy AWX using external PostgreSQL database](https://github.com/kurokobo/awx-on-k3s/blob/main/tips/external-db.md)" 😃
Thanks for providing request!
