### ISSUE TITLE
upgrade Gitea 

### ISSUE THREAD

**Issue by GDMTT** [kurokobo/awx-on-k3s#210]
## Environment
 

- OS: Ubuntu 22.04.2 LTS
- Kubernetes/v1.25.6+k3s
- AWX Operator: 2.0.1

## Description
How do I upgrade Gitea ? 
Update kustomization.yaml newTag: "1.18" to "1.19.1" ?
and run kubectl apply -k git

**Comment by kurokobo** [comment]
@GDMTT 
Hi, thanks for using my guide.

> Update kustomization.yaml newTag: "1.18" to "1.19.1" ?
> and run kubectl apply -k git

Correct. Gitea updates all data in DB during its startup. See https://docs.gitea.io/en-us/upgrade-from-gitea/
If you want to make a backup of your Gitea before upgrade, you can follow the backup guide for Gitea (<https://docs.gitea.io/en-us/backup-and-restore/>), or simply save `/data/git` on your k3s host.

```bash
# Shut down Gitea
$ kubectl -n git scale deployment/git --replicas=0

# Copy all files
$ sudo tar zcvf gitea.tar.gz /data/git

# Start Gitea
kubectl -n git scale deployment/git --replicas=1
```

**Comment by GDMTT** [comment]
Great thanks for taking time to answer my question.
