### ISSUE TITLE
Issue when building the custom EE environnement behind proxy

### ISSUE THREAD

**Issue by mehdia4ever** [kurokobo/awx-on-k3s#212]
## Environment

    OS: Ubuntu 20.04.6 LTS
    Ansible-builder: 1.2.0
    Docker-version: 20.10.21

## Description

Issue when building custom EE environnement behind corporate proxy.

Am having a issue when i am running my command to build a custom EE using your files in the builder repository.

## Step to Reproduce
ansible-builder build --tag localhost/custom-ee:1.0 --container-runtime docker --verbosity 3

my execution-environnement.yml

--
version: 1
build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/ansible/ansible-runner:stable-2.12-devel'
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "-c"
dependencies:
    python: requirements.txt
    galaxy: requirements.yml
additional_build_steps:
  prepend:
    - ENV http_proxy http://proxy:port
    - ENV https_proxy http://proxy:port
    - ENV HTTP_PROXY http://proxy:port
    - ENV HTTPS_PROXY http://proxy:port
## ERROR

Starting galaxy collection install process
Process install dependency map
[WARNING]: Skipping Galaxy server https://galaxy.ansible.com. Got an unexpected
error when getting available versions of collection awx.awx: Unknown error when
attempting to call Galaxy at 'https://galaxy.ansible.com/api/': <urlopen error
[Errno -2] Name or service not known>
ERROR! Unknown error when attempting to call Galaxy at 'https://galaxy.ansible.com/api/': <urlopen error [Errno -2] Name or service not known>

**Comment by mehdia4ever** [comment]
closed

**Comment by kurokobo** [comment]
@mehdia4ever 
Hi, thanks for updating. If you have time, could you please let me know what the root cause was for your issue?

**Comment by mehdia4ever** [comment]
Hi,
I have juste add proxy variables into append section, and it's works.
