### ISSUE TITLE
Not deploying

### ISSUE THREAD

**Issue by stefanpinter** [kurokobo/awx-on-k3s#22]
## Environment

- OS: Ubuntu 20.04
- Kubernetes/K3s:  v1.21.7+k3s1 (ac705709)
- AWX Operator: 0.15.0

## Description
Deployment in endless loop, worked once a few days ago, but not anymore

## Step to Reproduce
deploy via README.md (with acme issuer)

## Logs
...has timed out progressing.\", \"reason\": \"ProgressDeadlineExceeded\", \"status\": \"False\", \"type\": \"Progressing\"}], \"observedGeneration\": 1, \"replicas\": 1, \"unavailableReplicas\": 1, \"updatedReplicas\": 1}}}\n\r\nPLAY RECAP *********************************************************************\r\nlocalhost                  : 

ok=41   changed=0    unreachable=0    failed=1    skipped=30   rescued=0    ignored=0   
\r\n\n","job":"3116155310435672272","name":"awx","namespace":"awx","error":"exit status 2"}
{"level":"error","ts":1640068891.7860224,"logger":"controller-runtime.manager.controller.awx-controller","msg":"Reconciler error","name":"awx","namespace":"awx","error":"event runner on failed","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:214"}

**Comment by stefanpinter** [comment]
i uncommented these lines and now it is working again:
  web_resource_requirements: {}
  task_resource_requirements: {}
  ee_resource_requirements: {}

having 2 cores and 4GB though

**Comment by kurokobo** [comment]
> i uncommented these lines and now it is working again:

This is the answer.
The each nodes in kubernetes have "Capacity" value for CPU and memory, and each Pods running on kubernetes may have a "Request" value for the required CPU and memory. The total "Request" value cannot exceed the "Capacity" value of the node, so if there is not enough capacity, the AWX deployment will fail.

AWX and its PostgreSQL has default "Request" value, and that lines you uncommented will have the effect of removing the default "Request" value for the Pods for AWX and related PostgreSQL.

You can check the "Capacity" of a node and the "Request" value of running Pods with the following command.

```bash
$ kubectl describe node
...
Capacity:
  cpu:                4
  ephemeral-storage:  41152888Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             7996680Ki
  pods:               110
Allocatable:
  cpu:                4
  ephemeral-storage:  40033529416
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             7996680Ki
  pods:               110
...
Non-terminated Pods:          (11 in total)
  Namespace                   Name                                                CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
  ---------                   ----                                                ------------  ----------  ---------------  -------------  ---
  kube-system                 local-path-provisioner-5ff76fc89d-6w89h             0 (0%)        0 (0%)      0 (0%)           0 (0%)         25d
  cert-manager                cert-manager-cainjector-967788869-xnq2n             0 (0%)        0 (0%)      0 (0%)           0 (0%)         25d
  cert-manager                cert-manager-webhook-6668fbb57d-r9dmj               0 (0%)        0 (0%)      0 (0%)           0 (0%)         25d
  kube-system                 coredns-7448499f4d-h8g4k                            100m (2%)     0 (0%)      70Mi (0%)        170Mi (2%)     25d
  kube-system                 metrics-server-86cbb8457f-v5h4z                     0 (0%)        0 (0%)      0 (0%)           0 (0%)         25d
  kube-system                 svclb-traefik-gw76c                                 0 (0%)        0 (0%)      0 (0%)           0 (0%)         25d
  cert-manager                cert-manager-55658cdf68-rfqmf                       0 (0%)        0 (0%)      0 (0%)           0 (0%)         25d
  awx                         awx-7d74496d7d-d66dw                                2 (50%)       0 (0%)      4Gi (52%)        0 (0%)         12d
  awx                         awx-operator-controller-manager-6d95b9cb57-t6pd2    0 (0%)        0 (0%)      0 (0%)           0 (0%)         7d10h
  kube-system                 traefik-97b44b794-5pl47                             0 (0%)        0 (0%)      0 (0%)           0 (0%)         25d
  awx                         awx-postgres-0                                      0 (0%)        0 (0%)      0 (0%)           0 (0%)         12d
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests      Limits
  --------           --------      ------
  cpu                2100m (52%)   0 (0%)
  memory             4166Mi (53%)  170Mi (2%)
  ephemeral-storage  0 (0%)        0 (0%)
  hugepages-1Gi      0 (0%)        0 (0%)
  hugepages-2Mi      0 (0%)        0 (0%)
...
```

**Comment by kurokobo** [comment]
Closed do to inactivity. Feel free to re-open if your issue still exists.
