### ISSUE TITLE
upgrading awx

### ISSUE THREAD

**Issue by levcovenant** [kurokobo/awx-on-k3s#220]
I have successfully upgrade awx from 2.0.1 to 2.1.0 thanks to your guide
do I need to do something with awx-on-k3s? update this as well to 2.1.0 somehow?

I ask because in the deployment guide its also needed to do git clone https://github.com/kurokobo/awx-on-k3s.git and checkout the same version as the operator.

**Comment by kurokobo** [comment]
@levcovenant 
This is the diff between 2.0.1 and 2.1.0; https://github.com/kurokobo/awx-on-k3s/commit/8aacaa0dc0b2e908e58c5095009f5ea2bae098bb
As you can see there is no big changes between those versions, so usualy you can use the files for 2.0.1 for 2.1.0.
