### ISSUE TITLE
Update guide

### ISSUE THREAD

**Issue by kuchynkap** [kurokobo/awx-on-k3s#23]
Can you please create a guide for safely updating to a newer version of AWX Operator?

**Comment by kurokobo** [comment]
There is a guide to [upgrade AWX Operator from 0.13.0 or earlier to 0.14.0 or later](https://github.com/kurokobo/awx-on-k3s/blob/main/tips/upgrade-operator.md).

If you want to upgrade between two versions prior to 0.13.0 or between two versions after 0.14.0, simply redeploy AWX Operator.

**Comment by kuchynkap** [comment]
In my case it is from 0.14.0 to 0.15.0. Thank you, I will take a look!

**Comment by kurokobo** [comment]
So simply you shoud invoke:

```bash
# Prepare required files
git clone https://github.com/ansible/awx-operator.git
cd awx-operator
git checkout 0.15.0

# Re-deploy AWX Operator
export NAMESPACE=<The name of the namespace where your AWX Operator 0.14.0 exists>
make deploy
```

and just wait.

**Comment by kuchynkap** [comment]
Thank you!
