### ISSUE TITLE
Upgrade from operator version 1.3.0 to latest

### ISSUE THREAD

**Issue by bobby0724** [kurokobo/awx-on-k3s#230]
## Environment

- Ubuntu 22.04
- Kubernetes/K3s: 1.26.5+k3s1 (7cefebea)
- AWX Operator: 1.3.0

## Description

Hello i would like to know how can I upgrade my AWX instance running on version 1.3.0 to the latest level

## Step to Reproduce

I am running operator 1.3.0 and I would like to upgrade to the latest level but i do not know the process

**Comment by kurokobo** [comment]
See this page:

https://github.com/kurokobo/awx-on-k3s/blob/main/tips/upgrade-operator.md

**Comment by bobby0724** [comment]
thanks you
