### ISSUE TITLE
Please add to Requirements

### ISSUE THREAD

**Issue by daydone** [kurokobo/awx-on-k3s#246]
Environment
k3s version: v1.27.3+k3s1 (fe9604ca)
go version: go1.20.5
Operating System: CentOS 8

Description
The current installation requirements for the AWX deployment lack mention of a possible network configuration issue. In some cases, depending on the network configuration, the host may need to have the same hostname as the AWX deployment. This can lead to errors such as 404 or Bad Gateway.

Steps to Reproduce
Install on a network that uses DHCP and a DNS server.
Set the host's name as something other than what you want to call the AWX server.
Expected Behavior
The AWX deployment should work as expected, regardless of the host's hostname.

Actual Behavior
When the host's hostname is different from the desired AWX server name, it results in errors such as 404 or Bad Gateway.

Proposed Solution
Include as a requirement in the requirements section of the Readme

**Comment by kurokobo** [comment]
No such problem occurs in my environment. Please clarify the problem more specifically.

Regardless of the hostname of the k3s host, if the client can resolve the hostname of Ingress for AWX, AWX is accessible. In fact, my k3s host has a different name than the Ingress hostname.

**Comment by daydone** [comment]
The NS never resolves the hostname of the AWX server and if I added the association to /etc/hosts I would get a 'Bad Gateway" error in the browser.

**Comment by kurokobo** [comment]
I still can't reprocude. `hosts` file on client side should be work well.

I believe your issue is caused by some misconfiguration or very specific configuration of your network.

I can add small note for name resolution to README, but it would be very trivial note to require only that the client have to be able to resolve names for AWX using DNS server or the hosts file.

I've deployed AWX with hostname `hoge.fuga.piyo` on the host `kuro-awx01`.

```bash
$ hostname
kuro-awx01.krkb.lab

$ kubectl -n awx get ingress
NAME          CLASS     HOSTS            ADDRESS         PORTS     AGE
awx-ingress   traefik   hoge.fuga.piyo   192.168.0.219   80, 443   6m24s
```

This AWX can be accessed from cloents using `hosts` file instead of DNS server.

Windows client:

```powershell
# Windows client
PS> get-content C:\Windows\System32\drivers\etc\hosts
...
192.168.0.219 hoge.fuga.piyo
...

PS> invoke-webrequest https://hoge.fuga.piyo/api/

StatusCode        : 200
StatusDescription : OK
Content           : {"description":"AWX REST API","current_version":"/api/v2/","available_versions":{"v2":"/api/v2/"},"
                    oauth2":"/api/o/","custom_logo":"","custom_login_info":"","login_redirect_override":""}
...
```

```bash
# Linux client
$ cat /etc/hosts
...
192.168.0.219 hoge.fuga.piyo
...

$ curl -k https://hoge.fuga.piyo/api/
{"description":"AWX REST API","current_version":"/api/v2/","available_versions":{"v2":"/api/v2/"},"oauth2":"/api/o/","custom_logo":"","custom_login_info":"","login_redirect_override":""}
```

**Comment by daydone** [comment]
Fair enough, if it is not reproduceable it is probably something in my networks config. I appreciate your response.

**Comment by kurokobo** [comment]
@daydone 
If you need help to investigate your issue, provide actual configurations for your AWX and output from your troubleshooting (nslookup, dig, hosts file, curl, etc.)

**Comment by daydone** [comment]
I have the application working as making Hosts hostname = application hostname worked. I think you are right that this is probably caused by some network configuration that I am unaware of. Thank you!
