### ISSUE TITLE
Custom CA - DOC Clarifications

### ISSUE THREAD

**Issue by Dustin-Wi** [kurokobo/awx-on-k3s#263]
## Environment
k3s version v1.27.6+k3s1 (bd04941a)
go version go1.20.8

- OS: RHEL 8.8 (Ootpa)
- Kubernetes/K3s:
```
kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.27.6+k3s1
Kustomize Version: v5.0.1
Server Version: v1.27.6+k3s1
```
- AWX Operator: 2.5.3

## Description
While following the below guide, using Method 2: Mount Host File, there was one step I had to do differently.  As a beginner to CA Trust stores for Linux, I tripped over this for a while and I wanted to help anyone else who might have the same problem as a beginner.

[Trust Custom CA](https://github.com/kurokobo/awx-on-k3s/blob/main/tips/trust-custom-ca.md#method-2-mount-host-filesystem)

Specifically, this section:
[Modify options on AWX](https://github.com/kurokobo/awx-on-k3s/blob/main/tips/trust-custom-ca.md#modify-options-on-awx)
    
On `Settings` > `Jobs settings` > `Edit` page, modify following two options.
    
- Enable `Expose host paths for Container Groups`.
- Ensure `"/etc/pki/ca-trust:/etc/pki/ca-trust:O"` is specified in `Paths to expose to isolated jobs`.

I had to also add `"/etc/pki/tls:/etc/pki/tls:O"` to my `Paths to expose to isolated jobs` under Jobs Settings.

**Comment by kurokobo** [comment]
@Dustin-Wi 
Hi, thanks for filling the issue here.

> I had to also add `"/etc/pki/tls:/etc/pki/tls:O"` to my Paths to expose to isolated jobs under Jobs Settings.

Hmm it's not required in my lab, could you clarify which files under `/etc/pki/tls` are required to be available in your EE?

In my case, `/etc/pki/tls/cert.pem` is required in EE but it's not actual pem file but just a symbolic link to `/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem`, so mounting `/etc/pki/ca-trust` is enough to use updated `/etc/pki/tls/cert.pem`.

```bash
$ ls -l /etc/pki/tls/cert.pem
lrwxrwxrwx. 1 root root 49 Jun 17  2021 /etc/pki/tls/cert.pem -> /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
```

**Comment by Dustin-Wi** [comment]
This is the file that I needed access to:
/etc/pki/tls/cert.pem

It's the same symlink you mentioned.  I just removed the directory from the exposed list and my installation is still working.

The only change I made before and after it worked was that one directory.  The mistake is probably on my end.
