### ISSUE TITLE
WinRMTransportError: Bad HTTP response returned from server. Code 400

### ISSUE THREAD

**Issue by Nilesh486** [kurokobo/awx-on-k3s#264]
## Environment

- OS: CentOS 	CentOS Stream 8 .
- Kubernetes/K3s: 	K3s v1.25.5+k3s2
- AWX Operator: 21.11.0/1.1.4

Getting below error sometimes when client is trying to restart application through AWX tower. We have already made the winrm configuration but still whenever client want to take application service resatrt some times it got failed.

ERROR:

msg": "Unexpected failure during module execution: Bad HTTP response returned from server. Code 400",
  "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.9/site-packages/winrm/protocol.py\", line 248, in send_message\n    root = ET.fromstring(ex.response_text)\n  File \"/usr/lib64/python3.9/xml/etree/ElementTree.py\", line 1343, in XML\n    return parser.close()\nxml.etree.ElementTree.ParseError: no element found: line 1, column 0\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.9/site-packages/ansible/executor/task_executor.py\", line 165, in run\n    res = self._execute()\n  File \"/usr/local/lib/python3.9/site-packages/ansible/executor/task_executor.py\", line 660, in _execute\n    result = self._handler.run(task_vars=vars_copy)\n  File \"/usr/local/lib/python3.9/site-packages/ansible/plugins/action/normal.py\", line 39, in run\n    result = merge_hash(result, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))\n  File \"/usr/local/lib/python3.9/site-packages/ansible/plugins/action/__init__.py\", line 1179, in _execute_module\n    res = self._low_level_execute_command(cmd, sudoable=sudoable, in_data=in_data)\n  File \"/usr/local/lib/python3.9/site-packages/ansible/plugins/action/__init__.py\", line 1344, in _low_level_execute_command\n    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)\n  File \"/usr/local/lib/python3.9/site-packages/ansible/plugins/connection/winrm.py\", line 609, in exec_command\n    result = self._winrm_exec(cmd_parts[0], cmd_parts[1:], from_exec=True, stdin_iterator=stdin_iterator)\n  File \"/usr/local/lib/python3.9/site-packages/ansible/plugins/connection/winrm.py\", line 568, in _winrm_exec\n    self.protocol.cleanup_command(self.shell_id, command_id)\n  File \"/usr/local/lib/python3.9/site-packages/winrm/protocol.py\", line 390, in cleanup_command\n    res = self.send_message(xmltodict.unparse(req))\n  File \"/usr/local/lib/python3.9/site-packages/winrm/protocol.py\", line 251, in send_message\n    raise ex\n  File \"/usr/local/lib/python3.9/site-packages/winrm/protocol.py\", line 243, in send_message\n    resp = self.transport.send_message(message)\n  File \"/usr/local/lib/python3.9/site-packages/winrm/transport.py\", line 322, in send_message\n    response = self._send_message_request(prepared_request, message)\n  File \"/usr/local/lib/python3.9/site-packages/winrm/transport.py\", line 338, in _send_message_request\n    raise WinRMTransportError('http', ex.response.status_code, response_text)\nwinrm.exceptions.WinRMTransportError: Bad HTTP response returned from server. Code 400\n",

![Capture](https://github.com/kurokobo/awx-on-k3s/assets/19816425/3318ac0c-292a-42e0-ada8-c94d20d3a0be)

**Comment by kurokobo** [comment]
Lack of information. Have you tested your connection with `win_ping` module?

**Comment by Nilesh486** [comment]
Due to network package dropped issue was occured, Thanks for the reply . issue is resolved now
