### ISSUE TITLE
missing Tag for 2.7.1

### ISSUE THREAD

**Issue by christiangierschner** [kurokobo/awx-on-k3s#273]
Hi,

thank you very much for your work, really appreciated! We ourselves use your repository for our awx on k3s deployment. Our CI/CD clones your repo, checks out every tag and compares them to the local already synced tags. We're not getting a new release now, because you didn't create a new tag for 2.7.1...is this intended or did you just forget? 🙈

We need to know, because we would need to adjust our pipeline.

Thanks so much in Advance

Christian

**Comment by kurokobo** [comment]
Uh-oh sorry for this and thank you for informing me! Simply I just forgot adding tag for my commit, will work in next hour!

**Comment by kurokobo** [comment]
I just added tag 2.7.1. Sorry for inconvinience, thank you for letting me know!
