### ISSUE TITLE
Changing k3s default ingress from 80/443 to 8080/8443

### ISSUE THREAD

**Issue by toutas** [kurokobo/awx-on-k3s#288]
Is there a way to modify the setup so I am able to run awx on k3s alongside a docker-hosted traefik instance listening on 80/443? I have not been able to find a way to modify the k3s ingress for listening on 8080/8443 instead of 80/443. Currently I have modified my traefik instance in docker to listen to 8080/8443 instead, but I would prefer modifying the k3s ingress since awx is not accessed as often as my services behind traefik.

Any input is greatly appreciated.

**Comment by kurokobo** [comment]
Hi, yes, it is possible.

Create following config file.

```bash
sudo tee /var/lib/rancher/k3s/server/manifests/traefik-config.yaml <<EOF
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      web:
        exposedPort: 8080
      websecure:
        exposedPort: 8443
EOF
```

Then just wait for the pod `svclb-traefik-*` to be newly started (see `AGE` colmun).

```bash
]$ kubectl -n kube-system get pod
NAME                                      READY   STATUS      RESTARTS   AGE
...
svclb-traefik-60863cf7-s46mb              2/2     Running     0          3m46s
helm-install-traefik-m5xr6                0/1     Completed   0          3m48s
```

**Comment by toutas** [comment]
cheers, I will test this out tomorrow!

**Comment by toutas** [comment]
I performed the test, but it seems to just expose 8080/8443 without removing the 80/443. do I need some other modifications to remove 80/443 being listened to by the k3s traefik ingress?
