### ISSUE TITLE
Offline Upgrade

### ISSUE THREAD

**Issue by everydaylearner** [kurokobo/awx-on-k3s#291]
Hello,

Is there a way perform offline upgrade?  The host(s) i need to upgrade does not have any internet connectivity. Currently i am running
Operator: 0.23 
AWX 21.2.0
k3s version v1.23.6+k3s1

I would like to upgrade to latest version Operator/AWX then k3s at some point. Issue is that the host does not have any internet access. 

The procedure i was able to gather is;

1- Review notes from https://github.com/kurokobo/awx-on-k3s/blob/main/tips/upgrade-operator.md
especially "Note for upgrading from 0.25.0 or earlier to 0.26.0 or later" 
2- Download https://github.com/kurokobo/awx-on-k3s.git complete repo
3- Update base/awx.yaml, kustomization.yaml 
4- Git checkout ?

Do i need to download operator separately? 

Thank you!

**Comment by kurokobo** [comment]
Hi, thanks for filling the issue.

Offline upgrade is technically possible, but it is strongly recommended to connect to the internet temporarily and disconnect after the upgrade is done, if possible.

The hard point is, in addition to the files from AWX Operator, container images for AWX, AWX Operator, kube-rbac-proxy, and updated EE must also be downloaded and imported to containerd (or your private container registory). It will also be necessary to troubleshoot based on a sufficient understanding of the environment and architecture when the upgrade fails for whatever reason.

It is difficult to provide a complete step-by-step procedure, but roughly the steps are as follows

- Identify all container images that will be needed in the upgraded environment
- Download the required container images and import them into containerd ([see this guide to learn how to use `docker save` and `ctr images import`](https://github.com/kurokobo/awx-on-k3s/tree/main/builder#use-ee-in-awx-without-container-registry)), or place them in a private registry that can be used by your K3s
- Follow [the notes as you mentioned](https://github.com/kurokobo/awx-on-k3s/blob/main/tips/upgrade-operator.md#%EF%B8%8F-note-for-upgrading-from-0250-or-earlier-to-0260-or-later) to perform additional tasks
- Download files with the appropriate tags from the AWX Operator repository.
- Deploy a new Operator (using `make` or `kustomization.yaml`)

**Comment by everydaylearner** [comment]
thank you very much! i will explore it . I did not think about the container images. I think that may complicate things little more then i anticipated.
