### ISSUE TITLE
It works! Just needed to add to awx.yaml to fix Django CORS error

### ISSUE THREAD

**Issue by MrRoyce** [kurokobo/awx-on-k3s#294]
## Environment

K3s: 1.2.8

- OS: Ubuntu 20.04
- Kubernetes/K3s: K3s
- AWX Operator: X.Y.Z

## Description

Two issues that I had to fix to get this up and running

1. I originally had an ARM architecture for my VPS which caused the K3S deployment to fail with `exec /usr/local/bin/yarn: exec format error`.  This Reddit post said to switch to AMD/86 and that fixed the error: `https://www.reddit.com/r/kubernetes/comments/13lurdl/kubernetes_error_exec_usrlocalbinyarn_exec_format/`
2. I was then able to bring up the login page, but the login failed.  I used the logs command: `kubectl logs -f <pod name>` which showed the Djanjo CORS error.  This GH issue said to add extra vars to the K3s file: `https://github.com/ansible/awx/issues/14024`

After those 2 changes, I was able to login.  Thanks to Kurokobo for this great writeup and to the community at reddit and GH.

**Comment by kurokobo** [comment]
Hi, thanks for using my gjide.

I don't know why you've filled this issue as a bug report, but if you feel that there is some problem in the guide, could you provide actual versions for Operator and AWX, logs about CORS, and specs for your AWX (means `base/awx.yaml`)? Thanks!
