### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by jpmens** [kurokobo/awx-on-k3s#328]
Dear @kurokobo, I've been using this repository for setting up AWX ever since kubernetes was forced upon us for the program, and I finally want to  say "thank you!".

For someone like myself with only very limited knowledge about how the bits and pieces fit together, your repository and particularly its very good documentation are a life-saver.

Thank you ever so much!

**Comment by kurokobo** [comment]
Thank you for the kind words! I'm glad this guide was helpful.

It's not often that I get a chance to be thanked so clearly, I'm so glad, thank you too! I hope you continue to enjoy AWX 😃

**Comment by kurokobo** [comment]
I will keep this open until the bot closes this😃 Of course if you prefer to close this, you can do so. Thanks!

**Comment by Nikolay-Kr** [comment]
Thank you very much. Your repository helped me a lot

**Comment by alensfor** [comment]
I second jpmens and Nikolay, thanks so much for this excellent source (and the amazing detailed documentation !) for running AWX in k3s, this is gold !

**Comment by kurokobo** [comment]
@Nikolay-Kr @alensfor 
Thanks a lot for your support! Glad to support so many demands😃 I hope this guide will also be good first introduction to Kubernetes.
Have fun with AWX and K3s!
