### ISSUE TITLE
Any guide on connecting this to existing or old tower instance for data migration?

### ISSUE THREAD

**Issue by fahadshery** [kurokobo/awx-on-k3s#329]
Hi,

First of all, your guides are a life saver! Can't thank you enough... :)

I have an old tower instance running in docker. What's the best way to connect to it for data migration?

Thanks,

**Comment by fahadshery** [comment]
this guide is useless tbh...
My old AWX was deployed using docker...
I would love to see a section of connecting your AWX instance to the old AWX (docker) version and transfer data.

**Comment by kurokobo** [comment]
@fahadshery 
The official docs is the very docs to migrate data from docker based installation to kubernetes based installation.

You should:

- Gather your old `SECRET_KEY`. See `/etc/tower/SECRET_KEY` in the container
- Make your old PSQL on Docker accessible from your new K3s host

Then:

- Create secret that includes your old `SECRET_KEY`
- Create secret that includes credentials and connection information about your old PSQL
- Specify above secrets via `old_postgres_configuration_secret` and `secret_key_secret` in `base/awx.yaml`

**Comment by fahadshery** [comment]
Thanks for this, I will try it...
is there an easier method to transfer data from a different awx running on K3S?
The thing is I deployed one of my own awx instances using the official guide...
Then I tried your guide which enables me to access it using DNS. 
What's the best way to connect the new awx instance and do a data migration in this instance?

thanks again

**Comment by kurokobo** [comment]
> What's the best way to connect the new awx instance and do a data migration in this instance?

It is impossible to say for sure what is _best way_, as it depends on the environment, usage, and your expertise, but the migration guide is still valid option for you.

Technically, of course, there are several ways to migrate PSQL, but the process is a bit more complicated, as AWX will not work as expected unless not only the DB but also the SECRET_KEY is migrated, and the Operator and AWX Pods must be stopped before the migration is started.
If you are not familiar with the architecture of AWX and Operator, and Kubernetes, the migration guide is the easiest to follow, I think.

**Comment by fahadshery** [comment]
> * Create secret that includes your old `SECRET_KEY`
> * Create secret that includes credentials and connection information about your old PSQL
> * Specify above secrets via `old_postgres_configuration_secret` and `secret_key_secret` in `base/awx.yaml`

So I created 2 files within the `base` directory of your projects. one was having the `secret key` from the old PSQL and the other one had the PSQL info for the old Postgres.

I am getting this error constantly:

```bash
{"level":"info","ts":"2024-04-17T19:25:54Z","logger":"proxy","msg":"cache miss: /v1, Kind=PodList err-Index with name field:status.phase does not exist"}
{"level":"info","ts":"2024-04-17T19:26:00Z","logger":"proxy","msg":"cache miss: /v1, Kind=PodList err-Index with name field:status.phase does not exist"}
{"level":"info","ts":"2024-04-17T19:26:06Z","logger":"proxy","msg":"cache miss: /v1, Kind=PodList err-Index with name field:status.phase does not exist"}
{"level":"info","ts":"2024-04-17T19:26:12Z","logger":"proxy","msg":"cache miss: /v1, Kind=PodList err-Index with name field:status.phase does not exist"}
{"level":"info","ts":"2024-04-17T19:26:17Z","logger":"proxy","msg":"cache miss: /v1, Kind=PodList err-Index with name field:status.phase does not exist"}
{"level":"info","ts":"2024-04-17T19:26:23Z","logger":"proxy","msg":"cache miss: /v1, Kind=PodList err-Index with name field:status.phase does not exist"}
{"level":"info","ts":"2024-04-17T19:26:29Z","logger":"proxy","msg":"cache miss: /v1, Kind=PodList err-Index with name field:status.phase does not exist"}
{"level":"info","ts":"2024-04-17T19:26:35Z","logger":"proxy","msg":"cache miss: /v1, Kind=PodList err-Index with name field:status.phase does not exist"}
{"level":"info","ts":"2024-04-17T19:26:41Z","logger":"proxy","msg":"cache miss: /v1, Kind=PodList err-Index with name field:status.phase does not exist"}
{"level":"info","ts":"2024-04-17T19:26:47Z","logger":"proxy","msg":"cache miss: /v1, Kind=PodList err-Index with name field:status.phase does not exist"}
{"level":"info","ts":"2024-04-17T19:26:53Z","logger":"proxy","msg":"cache miss: /v1, Kind=PodList err-Index with name field:status.phase does not exist"}
{"level":"info","ts":"2024-04-17T19:26:58Z","logger":"proxy","msg":"cache miss: /v1, Kind=PodList err-Index with name field:status.phase does not exist"}
{"level":"info","ts":"2024-04-17T19:27:04Z","logger":"proxy","msg":"cache miss: /v1, Kind=PodList err-Index with name field:status.phase does not exist"}
```

**Comment by kurokobo** [comment]
@fahadshery 
Gather Operator's logs and determine which task is failed and why. Also Gather the status, events, and logs of your failed pods.
Refer to: https://github.com/kurokobo/awx-on-k3s/blob/main/tips/troubleshooting.md

**Comment by fahadshery** [comment]
I have tried again and the issue was that docker host was not accessible properly to the new awx instance.
But the issue now is that the new awx instance can connect to the Postgres running in the docker container. It finishes with no errors. But there is no new data ported over from the old Postgres. 
It creates a brand new database and that;s it!

**Comment by kurokobo** [comment]
@fahadshery 
Could you please provide step-by-step how did you perform migration?

**Comment by kurokobo** [comment]
Also complete logs from Operator is helpful to see if migration works as expected or not.
