### ISSUE TITLE
New UI Page Not Found

### ISSUE THREAD

**Issue by everydaylearner** [kurokobo/awx-on-k3s#346]
## Environment
k3s version v1.29.3+k3s1 (8aecc26b)
go version go1.21.8

    OS: Red Hat 9.3
    Kubernetes/K3s: 1.29.3
    AWX Operator: 2.15.0

## Description

The new UI_Next does not work some reason!  I upgraded my AWX version from previous version and everything is working as expected so far but the new UI is not activating some reason. When i click  I am getting "Page Not Found"  any tips how can get this troubleshooted?

Thank you!

**Comment by everydaylearner** [comment]
![2024-04-16 11_49_56-Window](https://github.com/kurokobo/awx-on-k3s/assets/37123843/c1ff1673-4c06-4900-97e5-635491dc3e0d)


screenshot is attached!

**Comment by kurokobo** [comment]
@everydaylearner 
Good find, this seems to be upstream issue, so could you please open new issue on ansible/awx repo?: https://github.com/ansible/awx

**Comment by kurokobo** [comment]
I'm closing this issue since this came from upstream instead of this repository.

**Comment by kurokobo** [comment]
@everydaylearner 
Thanks for opening new issue!: https://github.com/ansible/awx/issues/15120
