### ISSUE TITLE
Image pull docker.io/library/postgres:12 failure - where to configure image pull secret / credentials

### ISSUE THREAD

**Issue by unixsysadmin** [kurokobo/awx-on-k3s#35]
## Environment

- OS: RHEL 8.5
- Kubernetes/K3s: v1.22.6+k3s1 (3228d9cb)
- AWX Operator: 0.16.1

## Description
On a fresh install the postgres container is in 'ErrImagePull' state.

```
# kubectl -n awx get pod
NAME                                               READY   STATUS         RESTARTS   AGE
awx-operator-controller-manager-6d959bd7dd-9g786   2/2     Running        0          2m58s
awx-postgres-0                                     0/1     ErrImagePull   0          46s
```

Looking further it seems it is unable to pull the image from docker.io
```
# kubectl -n awx describe pod awx-postgres-0
  Warning  Failed            20s (x2 over 50s)  kubelet            Error: ImagePullBackOff
  Normal   Pulling           6s (x3 over 54s)   kubelet            Pulling image "postgres:12"
  Warning  Failed            3s (x3 over 50s)   kubelet            Failed to pull image "postgres:12": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/postgres:12": failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/library/postgres/manifests/sha256:ed97ef00029e0df606e9d8c9fba68b1ef5d023dbacc84178b441312282178123: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

I think I understand the error - I have a login for docker hub, but I have not specified it anywhere so my requests are being denied.

This is very much identical to [Image pull failing on K3S deployment using kurokobo/awx-on-k3s
](https://www.reddit.com/r/kubernetes/comments/pyokim/image_pull_failing_on_k3s_deployment_using/)

I see references to `image_pull_secret` in the AWX Operator guide, but I'm unsure how to use them in conjunction with this guide.

What are the options for specifying credentials to docker hub?

## Step to Reproduce

Follow the guide on a fresh installation, but do not provide any docker hub credentials or run 'docker login'.

**Comment by kurokobo** [comment]
@unixsysadmin 
Right, you have reached the rate limit on Docker Hub since you didn't specify your credential.
There are various ways to solve this, here is the one of these way;

1. Create Secret by specifying username and password manually
   ```bash
   # If you don't have awx namespace, create it first,
   $ kubectl create ns awx

   # then create Secret in awx namespace.
   $ DOCKERHUB_USERNAME=<Your Username for Docker Hub>
   $ DOCKERHUB_PASSWORD=<Your Password or Personal Access Token for Docker Hub>
   $ kubectl -n awx create secret docker-registry awx-registry-secret \
       --docker-server=docker.io \
       --docker-username=${DOCKERHUB_USERNAME} \
       --docker-password=${DOCKERHUB_PASSWORD}
2. Append `image_pull_secret` to your `awx.yml`
   ```yaml
   spec:
     ...
     image_pull_secret: awx-registry-secret     👈👈👈
   ```
3. Apply it
   ```bash
   $ kubectl apply -k base
   ```

**Comment by unixsysadmin** [comment]
Thank you - let me try this out!

**Comment by unixsysadmin** [comment]
Thank you @kurokobo for the quick response and detailed explanation.

The method above worked well, as did the new guide you created (tested with Operator 0.16.1).

**Comment by kurokobo** [comment]
Good to hear that, will close this issue. Have fun 🚀
