### ISSUE TITLE
AWX tower URL redirection

### ISSUE THREAD

**Issue by Nilesh486** [kurokobo/awx-on-k3s#368]
Production environment

- OS: CentOS OEL 
- Kubernetes/K3s: K3s
- AWX Operator: 23.8.0

## Description
We have awx setup and the URL is https:/<<OLD URL>>// and we wanted to change the old url to new URL  https://<<new url>>.

Do we have provision to redirect the old url to new url.

**Comment by kurokobo** [comment]
@Nilesh486 
Hi, sorry for the late reply, I haven't been feeling well and couldn't find the time to respond.

> We have awx setup and the URL is https:/<>// and we wanted to change the old url to new URL https://<>.

Lack of information, but am I correct that you want to redirect users from `https://old-url-of-awx.example.com/` for your old AWX on K3s to `https://new-url-of-awx.example.com/`?
If so, technically we can use [RedirectRegex](https://doc.traefik.io/traefik/middlewares/http/redirectregex/) feature of Traefik to redirect users, but it also requires additional expertise with Traefik, Ingress, K3s, AWX Operator, SNI, etc.
It is out of scope to provide a complete guide here, so if you are interested, give it a try.

If you want a quick fix, you can run the web server with the old URL to redirect users, for example.
