### ISSUE TITLE
Change tls crt and key

### ISSUE THREAD

**Issue by komiko1** [kurokobo/awx-on-k3s#379]
## Environment
- OS: Ubuntu20.04
- Kubernetes/K3s: v1.30.2+k3s2
- AWX Operator: 2.19.1

## Description
I installed awx using kurokobo awx-on-k3s. It is working properly.
I need to change the old tls with a new one. Both old and new tls have been issued locally by me.
Could you please let me know how can I do this?
I'd appreciate it if you give me a detailed instruction to do this. Thank you.

**Comment by jpmens** [comment]
Install your `tls.{key,crt` into the `base/` directory of where you installed the clone of this repository, and re-apply that. I script this roughly as

```
cp $p1 /root/awx-on-k3s/base/tls.crt
/usr/local/bin/kubectl apply -k base
```

**Comment by kurokobo** [comment]
@komiko1 
Hi, as @jpmens described, just replace your `tls.crt` and `tls.key`, then invoke `kubectl apply -k base` again. Note that the crt and key files must be in PEM format.

@jpmens 
Thanks for your help!

**Comment by komiko1** [comment]
@jpmens @kurokobo 
Thank you both for your guidance.
