### ISSUE TITLE
How to install awx on microk8s?

### ISSUE THREAD

**Issue by komiko1** [kurokobo/awx-on-k3s#383]
Is this possible to install AWX using this repository files on Microk8s?
If yes, could you explain it please?

**Comment by kurokobo** [comment]
@komiko1 
If you are using single node Microk8s, yes, almost same procedure can be applied.
If not, [my previous comment](https://github.com/kurokobo/awx-on-k3s/issues/380#issuecomment-2222740368) should be considered.

No matter which Kubernetes distribution you're using, one thing I can say is that you should try it yourself and go through some trial and error before asking me for a complete explanation.
There's no reason or benefit for me to spend a lot of time verifying the complete procedure and organizing the steps on your behalf just to answer a question that took you only a few seconds to write.
