### ISSUE TITLE
Unable to add custom CA using mount host filesystem option

### ISSUE THREAD

**Issue by raamee** [kurokobo/awx-on-k3s#384]
## Environment

- OS: Rocky linux 9.4 (minimal)
- Kubernetes/K3s: k3s version v1.29.6+k3s2 (b4b156d9) / go version go1.21.11
- AWX Operator: 2.19.1
- AWX 24.6.1 

## Description

First of all, a big salute to you for creating this project. You have simplified AWX for millions of people. Now, coming to the issue, I am trying to add a custom CA which is required by my project by following the method mentioned here: https://github.com/kurokobo/awx-on-k3s/blob/main/tips/trust-custom-ca.md#method-2-mount-host-filesystem but still the custom CA is not getting added and I cannot sync the project.

Error: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local

## Step to Reproduce

I have followed this : https://github.com/kurokobo/awx-on-k3s/blob/main/tips/trust-custom-ca.md#method-2-mount-host-filesystem

but still  I am getting the error "Error: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local"

I confirm that the custom CA is successfully added in the host and it is working properly.

## Logs
I am not sure how to debug this. Kindly requesting your help.

Thank you.

**Comment by raamee** [comment]
I had to use this method - https://github.com/kurokobo/awx-on-k3s/blob/main/tips/trust-custom-ca.md#modify-basekustomizationyaml to be able to solve this issue.

Thank you and sorry for raising the issue without trying the first one.

**Comment by kurokobo** [comment]
@raamee 
I'm glad you made the attempt to solve the problem yourself, thanks for the update.
Enjoy!
