### ISSUE TITLE
pod/awx-operator-controller-manager - ErrImagePull

### ISSUE THREAD

**Issue by ViniciusDSBarbosa** [kurokobo/awx-on-k3s#388]
## Environment

- OS: Ubuntu 24.04
- Kubernetes/K3s:k3s version v1.30.4+k3s1 (98262b5d)
go version go1.22.5
- AWX Operator: 2.19.0

## Description

When following the installation guide after i apply the kubectl apply -k operator it returns this:
NAME                                                   READY   STATUS         RESTARTS   AGE
pod/awx-operator-controller-manager-666ddcf9c5-p6qz9   1/2     ErrImagePull   0          4m19s

NAME                                                      TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
service/awx-operator-controller-manager-metrics-service   ClusterIP   x.x.x.x   <none>        8443/TCP   2d22h

NAME                                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/awx-operator-controller-manager   0/1     1            0           4m19s

NAME                                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/awx-operator-controller-manager-666ddcf9c5   1         1         0       4m19s

## Step to Reproduce

Just trying to run the deploy always does this.

## Logs

kubectl -n awx logs awx-operator-controller-manager-666ddcf9c5-p6qz9 -c awx-manager
Error from server (BadRequest): container "awx-manager" in pod "awx-operator-controller-manager-666ddcf9c5-p6qz9" is waiting to start: trying and failing to pull image

Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  13m                     default-scheduler  Successfully assigned awx/awx-operator-controller-manager-666ddcf9c5-p6qz9 to lrsdocker
  Normal   Pulled     13m                     kubelet            Container image "gcr.io/kubebuilder/kube-rbac-proxy:v0.15.0" already present on machine
  Normal   Created    13m                     kubelet            Created container kube-rbac-proxy
  Normal   Started    13m                     kubelet            Started container kube-rbac-proxy
  Normal   BackOff    11m (x5 over 13m)       kubelet            Back-off pulling image "quay.io/ansible/awx-operator:2.19.1"
  Warning  Failed     11m (x5 over 13m)       kubelet            Error: ImagePullBackOff
  Normal   Pulling    11m (x4 over 13m)       kubelet            Pulling image "quay.io/ansible/awx-operator:2.19.1"
  Warning  Failed     11m (x4 over 13m)       kubelet            Error: ErrImagePull
  Warning  Failed     11m (x4 over 13m)       kubelet            Failed to pull image "quay.io/ansible/awx-operator:2.19.1": rpc error: code = NotFound desc = failed to pull and unpack image "quay.io/ansible/awx-operator:2.19.1": failed to extract layer sha256:6615b78892ea34be3c21bbafaa1cb16d8d3ab9a7b5e542228aba3af09cf286e4: failed to get reader from content store: blob sha256:9e9d81df23bfffb191ee1ccf45a9201930f96f9ee53d1e90aee4aa664e2dcec4 expected at /var/lib/rancher/k3s/agent/containerd/io.containerd.content.v1.content/blobs/sha256/9e9d81df23bfffb191ee1ccf45a9201930f96f9ee53d1e90aee4aa664e2dcec4: blob not found: not found
  Normal   Pulling    7m39s (x4 over 9m23s)   kubelet            Pulling image "quay.io/ansible/awx-operator:2.19.1"
  Warning  Failed     7m32s (x4 over 9m17s)   kubelet            Failed to pull image "quay.io/ansible/awx-operator:2.19.1": rpc error: code = NotFound desc = failed to pull and unpack image "quay.io/ansible/awx-operator:2.19.1": failed to extract layer sha256:6615b78892ea34be3c21bbafaa1cb16d8d3ab9a7b5e542228aba3af09cf286e4: failed to get reader from content store: blob sha256:9e9d81df23bfffb191ee1ccf45a9201930f96f9ee53d1e90aee4aa664e2dcec4 expected at /var/lib/rancher/k3s/agent/containerd/io.containerd.content.v1.content/blobs/sha256/9e9d81df23bfffb191ee1ccf45a9201930f96f9ee53d1e90aee4aa664e2dcec4: blob not found: not found
  Warning  Failed     7m32s (x4 over 9m17s)   kubelet            Error: ErrImagePull
  Warning  Failed     7m9s (x6 over 8m47s)    kubelet            Error: ImagePullBackOff
  Normal   BackOff    4m18s (x17 over 8m47s)  kubelet            Back-off pulling image "quay.io/ansible/awx-operator:2.19.1"

```bash
$ kubectl ...
...
```

## Files

```yaml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
...
```

**Comment by ViniciusDSBarbosa** [comment]
I've also tried pulling the image manually with: sudo ctr -n k8s.io images pull quay.io/ansible/awx-operator:2.19.1
and recreating the deploy automatically kubectl -n awx delete deployment awx-operator-controller-manager, but it didn't work.

**Comment by kurokobo** [comment]
@ViniciusLRS 
Hi, I can't reproduce this with K3s v1.30.4+k3s1 (98262b5d).
Do you also have Docker installed on the same host? How about pulling the image with `ctr` that bundled with K3s?

```bash
$ sudo $(which k3s) ctr version
Client:
  Version:  v1.7.20-k3s1
  Revision: 
  Go version: go1.22.5

Server:
  Version:  v1.7.20-k3s1
  Revision: 
  UUID: 522cb888-de4b-4d8a-a65f-0f16c831e5ea

$ sudo $(which k3s) ctr images pull quay.io/ansible/awx-operator:2.19.1
quay.io/ansible/awx-operator:2.19.1:                                              resolved       |++++++++++++++++++++++++++++++++++++++| 
index-sha256:7302e0c8e5a79c11275848b36c63c61d8e7487840164c109b7cda9aa93456901:    done           |++++++++++++++++++++++++++++++++++++++| 
manifest-sha256:53ac69ccc5d8f492f92daa9bfee894797a3aa091bc9291c80b333ebc04779a33: done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:5b32d6f53e1450bc1acf105cd06ba4e6ca7308f50c0498b8924cb0add34b1f3e:    done           |++++++++++++++++++++++++++++++++++++++| 
config-sha256:aa5cb2212d4a4c245411b936210a67b38ee770119f13ffd081a8736b00810029:   done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:aa42ef82fc0a877a3d1d411ac1a4a1eb6fdd883305b2eb045e380c282713ed29:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:c85dbc345e424c1750e445788c373b5dc85b0d16c32aabec7ccad2cd2fdc219c:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:70cefc523b6fb9a8f6d18a9e2d442859a7cf5b8b8fbe9a74e6119d643ea88072:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:9e9d81df23bfffb191ee1ccf45a9201930f96f9ee53d1e90aee4aa664e2dcec4:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:3f5404ef10f7d62ca19eac9c40963e6575409df22ac3515ceabd592ab7772819:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:cbce962608b472cbcc09880237ed9601dd89795c8ecf00576b6a8dfe78e84f7c:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:a5d13ce273573ecd61fbbdd7999f4ad89a294928b90fc24911e4e7c07944550d:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:d3bdeaa993667629ed8ecbeea2d0e02fccf4874ac3f413fbaf46d7148d8ca3ad:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:eb8c3b3bc0415b412c5d7846f4816682af9e874ae6eed998a6b47167d00ece44:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:cae2cd2759432614cd91f65b55e8dd454423004f014faad7ccb73a9961c36e81:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:39b59758f74e8ab8f2c9bbc76d4251229f212a5ec1f22f4e7411f57722272010:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:d9f7c845fdb6108a822e3495aa71e996d18e39d3cf18efb385e8b2c147568f55:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:2bdf0579469bebe79fbf1710755c354e31748e9b1498d6835e3d36e7b487c9fe:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:6ec3d9da243fcd40f482051afaca2aa7b45199a88e0540faaa7413e72dcad320:    done           |++++++++++++++++++++++++++++++++++++++| 
elapsed: 0.8 s                                                                    total:   0.0 B (0.0 B/s)                                         
unpacking linux/amd64 sha256:7302e0c8e5a79c11275848b36c63c61d8e7487840164c109b7cda9aa93456901...
done: 12.42833ms
```

**Comment by ViniciusDSBarbosa** [comment]
@kurokobo 
Hi!, yes docker is installed, i've tried pulling the image with **ctr** and after a sucessfull pull this is the error that shows:

**awx-operator-controller-manager-666ddcf9c5-n6rqq   1/2     CreateContainerError**

So i've tried running a the image locally:
**sudo $(which k3s) ctr run --rm quay.io/ansible/awx-operator:2.19.1 test-container**
And got this:
**INFO[0005] apply failure, attempting cleanup             error="failed to extract layer sha256:6615b78892ea34be3c21bbafaa1cb16d8d3ab9a7b5e542228aba3af09cf286e4: failed to get reader from content store: blob sha256:9e9d81df23bfffb191ee1ccf45a9201930f96f9ee53d1e90aee4aa664e2dcec4 expected at /var/lib/rancher/k3s/agent/containerd/io.containerd.content.v1.content/blobs/sha256/9e9d81df23bfffb191ee1ccf45a9201930f96f9ee53d1e90aee4aa664e2dcec4: blob not found: not found" key="extract-376102071-jxFB sha256:22a6f5f90ef6123ccf705c3ccad80fa969e4a93d039a9e012e2207b21f9fce95"
ctr: failed to extract layer sha256:6615b78892ea34be3c21bbafaa1cb16d8d3ab9a7b5e542228aba3af09cf286e4: failed to get reader from content store: blob sha256:9e9d81df23bfffb191ee1ccf45a9201930f96f9ee53d1e90aee4aa664e2dcec4 expected at /var/lib/rancher/k3s/agent/containerd/io.containerd.content.v1.content/blobs/sha256/9e9d81df23bfffb191ee1ccf45a9201930f96f9ee53d1e90aee4aa664e2dcec4: blob not found: not found**

Also some things i've tried:
sudo kubectl logs awx-operator-controller-manager-666ddcf9c5-n6rqq -n awx -c awx-manager
Error from server (BadRequest): container "awx-manager" in pod "awx-operator-controller-manager-666ddcf9c5-n6rqq" is waiting to start: CreateContainerError

sudo kubectl describe pod awx-operator-controller-manager-666ddcf9c5-n6rqq -n awx
Name:             awx-operator-controller-manager-666ddcf9c5-n6rqq
Namespace:        awx
Priority:         0
Service Account:  awx-operator-controller-manager
Node:            hostname/x.x.x.x
Start Time:       Mon, 02 Sep 2024 18:13:56 +0000
Labels:           control-plane=controller-manager
                  pod-template-hash=666ddcf9c5
Annotations:      kubectl.kubernetes.io/default-container: awx-manager
Status:           Pending
IP:               x.x.x.x
IPs:
  IP:           x.x.x.x
Controlled By:  ReplicaSet/awx-operator-controller-manager-666ddcf9c5
Containers:
  kube-rbac-proxy:
    Container ID:  containerd://175b3cd10769530ddb318364ef27850ee8d9cf575647e5f68e577e9de544a778
    Image:         gcr.io/kubebuilder/kube-rbac-proxy:v0.15.0
    Image ID:      gcr.io/kubebuilder/kube-rbac-proxy@sha256:d8cc6ffb98190e8dd403bfe67ddcb454e6127d32b87acc237b3e5240f70a20fb
    Port:          8443/TCP
    Host Port:     0/TCP
    Args:
      --secure-listen-address=0.0.0.0:8443
      --upstream=http://127.0.0.1:8080/
      --logtostderr=true
      --v=0
    State:          Running
      Started:      Mon, 02 Sep 2024 18:13:58 +0000
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     500m
      memory:  128Mi
    Requests:
      cpu:        5m
      memory:     64Mi
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-26vlz (ro)
  awx-manager:
    Container ID:
    Image:         quay.io/ansible/awx-operator:2.19.1
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Args:
      --health-probe-bind-address=:6789
      --metrics-bind-address=127.0.0.1:8080
      --leader-elect
      --leader-election-id=awx-operator
    State:          Waiting
      Reason:       CreateContainerError
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     1500m
      memory:  960Mi
    Requests:
      cpu:      50m
      memory:   32Mi
    Liveness:   http-get http://:6789/healthz delay=15s timeout=1s period=20s #success=1 #failure=3
    Readiness:  http-get http://:6789/readyz delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment:
      ANSIBLE_GATHERING:   explicit
      ANSIBLE_DEBUG_LOGS:  false
      WATCH_NAMESPACE:     awx (v1:metadata.namespace)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-26vlz (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   True
  Initialized                 True
  Ready                       False
  ContainersReady             False
  PodScheduled                True
Volumes:
  kube-api-access-26vlz:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason   Age                   From     Message
  ----    ------   ----                  ----     -------
  Normal   Scheduled  61s                default-scheduler  Successfully assigned awx/awx-operator-controller-manager-666ddcf9c5-kmz7l to lrsdocker
  Normal   Pulled     60s                kubelet            Container image "gcr.io/kubebuilder/kube-rbac-proxy:v0.15.0" already present on machine
  Normal   Created    60s                kubelet            Created container kube-rbac-proxy
  Normal   Started    59s                kubelet            Started container kube-rbac-proxy
  Warning  Failed     14s (x4 over 55s)  kubelet            Error: failed to create containerd container: error unpacking image: failed to extract layer sha256:6615b78892ea34be3c21bbafaa1cb16d8d3ab9a7b5e542228aba3af09cf286e4: failed to get reader from content store: blob sha256:9e9d81df23bfffb191ee1ccf45a9201930f96f9ee53d1e90aee4aa664e2dcec4 expected at /var/lib/rancher/k3s/agent/containerd/io.containerd.content.v1.content/blobs/sha256/9e9d81df23bfffb191ee1ccf45a9201930f96f9ee53d1e90aee4aa664e2dcec4: blob not found: not found
  Normal   Pulled     1s (x5 over 59s)   kubelet            Container image "quay.io/ansible/awx-operator:2.19.1" already present on machine

Also tried this to recreate the pod:
**kubectl delete pod awx-operator-controller-manager-666ddcf9c5-n6rqq -n awx**

**Comment by kurokobo** [comment]
@ViniciusLRS 
> expected at /var/lib/rancher/k3s/agent/containerd/io.containerd.content.v1.content/blobs/sha256/9e9d81df23bfffb191ee1ccf45a9201930f96f9ee53d1e90aee4aa664e2dcec4: blob not found: not found

This is the layer for `COPY /usr/local/lib/python3.9/site-packages /usr/local/lib/python3.9/site-packages # buildkit`: https://quay.io/repository/ansible/awx-operator/manifest/sha256:53ac69ccc5d8f492f92daa9bfee894797a3aa091bc9291c80b333ebc04779a33?tab=layers

```bash
$ cp /var/lib/rancher/k3s/agent/containerd/io.containerd.content.v1.content/blobs/sha256/9e9d81df23bfffb191ee1ccf45a9201930f96f9ee53d1e90a
ee4aa664e2dcec4 .

$ tar xvf 9e9d81df23bfffb191ee1ccf45a9201930f96f9ee53d1e90aee4aa664e2dcec4
usr/
usr/local/
usr/local/lib64/
usr/local/lib64/python3.9/
usr/local/lib64/python3.9/site-packages/
usr/local/lib64/python3.9/site-packages/MarkupSafe-2.1.3.dist-info/
...
```

Is there a possibility that your security software is mistakenly quarantining this layer?

```bash
$ docker pull quay.io/ansible/awx-operator:2.19.1
$ docker save quay.io/ansible/awx-operator:2.19.1 -o image.tar
$ tar xf image.tar

$ ls -l blobs/sha256/6615b78892ea34be3c21bbafaa1cb16d8d3ab9a7b5e542228aba3af09cf286e4 
-rw-r--r--. 1 kuro kuro 20150272 Jul  3 05:40 blobs/sha256/6615b78892ea34be3c21bbafaa1cb16d8d3ab9a7b5e542228aba3af09cf286e

$ tar xvf blobs/sha256/6615b78892ea34be3c21bbafaa1cb16d8d3ab9a7b5e542228aba3af09cf286e4
```

Also can you run the image on docker on the same host?

```bash
docker run --rm quay.io/ansible/awx-operator:2.19.1
```

**Comment by ViniciusDSBarbosa** [comment]
@kurokobo
cp commando returns:
cp: cannot stat '/var/lib/rancher/k3s/agent/containerd/io.containerd.content.v1.content/blobs/sha256/9e9d81df23bfffb191ee1ccf45a9201930f96f9ee53d1e90aee4aa664e2dcec4': No such file or directory
i've checked the name of the file and its the right one, also for now i'm not using any security software.
Upon doing the docker save and umcompressing the image.tar again no such file or directory:
ls -l blobs/sha256/6615b78892ea34be3c21bbafaa1cb16d8d3ab9a7b5e542228aba3af09cf286e4
ls: cannot access 'blobs/sha256/6615b78892ea34be3c21bbafaa1cb16d8d3ab9a7b5e542228aba3af09cf286e4': No such file or directory
Also when trying to run the image on docker:
docker run --rm quay.io/ansible/awx-operator:2.19.1
{"level":"info","ts":"2024-09-03T15:24:27Z","logger":"cmd","msg":"Version","Go Version":"go1.20.12","GOOS":"linux","GOARCH":"amd64","ansible-operator":"v1.34.0","commit":"d26c43bf94960d292152862a6685696be33190fb"}
{"level":"error","ts":"2024-09-03T15:24:27Z","logger":"controller-runtime.client.config","msg":"unable to load in-cluster config","error":"unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined","stacktrace":"sigs.k8s.io/controller-runtime/pkg/client/config.loadConfig.func1\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/client/config/config.go:133\nsigs.k8s.io/controller-runtime/pkg/client/config.loadConfig\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/client/config/config.go:155\nsigs.k8s.io/controller-runtime/pkg/client/config.GetConfigWithContext\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/client/config/config.go:97\nsigs.k8s.io/controller-runtime/pkg/client/config.GetConfig\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/client/config/config.go:77\ngithub.com/operator-framework/ansible-operator-plugins/internal/cmd/ansible-operator/run.run\n\tansible-operator-plugins/internal/cmd/ansible-operator/run/cmd.go:113\ngithub.com/operator-framework/ansible-operator-plugins/internal/cmd/ansible-operator/run.NewCmd.func1\n\tansible-operator-plugins/internal/cmd/ansible-operator/run/cmd.go:81\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039\nmain.main\n\tansible-operator-plugins/cmd/ansible-operator/main.go:40\nruntime.main\n\t/opt/hostedtoolcache/go/1.20.12/x64/src/runtime/proc.go:250"}
{"level":"error","ts":"2024-09-03T15:24:27Z","logger":"cmd","msg":"Failed to get config.","error":"invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable","errorCauses":[{"error":"no configuration has been provided, try setting KUBERNETES_MASTER environment variable"}],"stacktrace":"github.com/operator-framework/ansible-operator-plugins/internal/cmd/ansible-operator/run.run\n\tansible-operator-plugins/internal/cmd/ansible-operator/run/cmd.go:115\ngithub.com/operator-framework/ansible-operator-plugins/internal/cmd/ansible-operator/run.NewCmd.func1\n\tansible-operator-plugins/internal/cmd/ansible-operator/run/cmd.go:81\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039\nmain.main\n\tansible-operator-plugins/cmd/ansible-operator/main.go:40\nruntime.main\n\t/opt/hostedtoolcache/go/1.20.12/x64/src/runtime/proc.go:250"}

**Comment by ViniciusDSBarbosa** [comment]
I've also tried this:
sudo docker run --rm -e KUBECONFIG=/root/.kube/config -v /etc/rancher/k3s/k3s.yaml:/root/.kube/config quay.io/ansible/awx-operator:2.19.1
Same error as before.

**Comment by kurokobo** [comment]
Can you share the full output from following commands? Paste here or send me an e-mail by attaching log file.

```bash
uname -a
cat /etc/os-release 

sudo $(which k3s) ctr version
sudo $(which k3s) ctr images rm quay.io/ansible/awx-operator:2.19.1
sudo $(which k3s) ctr images pull quay.io/ansible/awx-operator:2.19.1
ls -l /var/lib/rancher/k3s/agent/containerd/io.containerd.content.v1.content/blobs/sha256/

sudo $(which k3s) crictl version
sudo $(which k3s) crictl rmi quay.io/ansible/awx-operator:2.19.1
sudo $(which k3s) crictl pull quay.io/ansible/awx-operator:2.19.1
sudo $(which k3s) crictl inspecti quay.io/ansible/awx-operator:2.19.1

docker rmi quay.io/ansible/awx-operator:2.19.1
docker pull quay.io/ansible/awx-operator:2.19.1
docker inspect docker pull quay.io/ansible/awx-operator:2.19.1
```

**Comment by ViniciusDSBarbosa** [comment]
There you go, also thanks for helping me out.
[CommandOutputs.txt](https://github.com/user-attachments/files/16852446/CommandOutputs.txt)

**Comment by ViniciusDSBarbosa** [comment]
Hi @kurokobo, i don't really know how the issue was solved probably the last command you asked me for the output did it but it worked out and i've sucessfully deployed AWX, thank you very much

**Comment by kurokobo** [comment]
@ViniciusLRS 
Thanks for the update, I don't know what caused it but I'm glad it's resolved 😃 Enjoy!
