### ISSUE TITLE
Long start time for AWX jobs - AWX 24.6.1 

### ISSUE THREAD

**Issue by vinothravindhran** [kurokobo/awx-on-k3s#392]
@kurokobo 

## Environment
k3s version v1.29.6+k3s2 (b4b156d9)
go version go1.21.11

- OS: RHEL 9.3
- Kubernetes/K3s: v1.29.6+k3s2
- AWX Operator: 2.19.1

## Description
Long start time for AWX jobs

I have recently installed AWX 24.6.1 in RHEL 9 machine and i have synced my projects playbook but while i try simple ping playbook, it took 2 mins to complete the job. I have attached screen shot. Please help me to fix it.
I have referred previous topics and applied necessary changed but still same slowness issue. I have attached refence image.

I’ve got a issue with jobs taking a “long” time to start 1 min 30 secs. scaling up the resources on the node has also been done but no improvements. Also I have referred AWX forum and changed some settings but still no luck.

I have pasted one playbook output and it took 2 min 29 secs to complete. Even simple ping play book take 1 min 30sec for single host.

Please advise us incase of any suggestions to fix the error.

I have attached logs. For your reference.

## Logs

Attached 

## Files

```
[Uploading AWX log.txt…]()


I have attached logs. For your reference.

**Comment by kurokobo** [comment]
@vinothravindhran 
Hi, I saw you on the forum, so I'd like to discuss this topic there. Please give me some time to respond.
https://forum.ansible.com/t/awx-slowness-issue-long-start-time-for-jobs-awx-24-6-1/8696?u=kurokobo
