### ISSUE TITLE
No Working with Linux(Centos/Ubuntu): Mux_client_read_packet: read header failed: Broken pipe

### ISSUE THREAD

**Issue by MartinGM81** [kurokobo/awx-on-k3s#394]
## Environment
k3s version v1.29.6+k3s2 (b4b156d9)
go version go1.21.11

- OS: CentOS 9, .
- Kubernetes/K3s: v1.29.6+k3s2
- AWX Operator: 2.19.1 , 2.18 and 2.11.0

## Description
My team has installed AWX [(Kurokobo - awx-on-k3s)], we have worked with Windows servers without problems, however, it does not work with any Linux distribution, since in all our tests we get the error:
**mux_client_read_packet: header read failed: broken pipe**

[job_50.txt](https://github.com/user-attachments/files/17168168/job_50.txt)

**Comment by kurokobo** [comment]
@MartinGM81 
Hi, could you please share the actual commands that you are trying to invoke with command module?
Also have you tested the connection with the `ansible.builtin.ping` module?

**Comment by kurokobo** [comment]
@MartinGM81 
Hi, I found you on the forum with the same question.
https://forum.ansible.com/t/awx-ssh-debug-mux-client-read-packet-read-header-failed-broken-pipe/8827

Please do not post the same question in different places unless you explicitly mention that you have posted it elsewhere and provide the link to it. Even if a question you submitted to a particular place receives a response, others may not be aware of it from different places. Someone unaware of this might spend their time in good faith trying to help you elsewhere, which is not ideal.

Let's move on to the forum.
