### ISSUE TITLE
Installing Harbor on the k3 as awx

### ISSUE THREAD

**Issue by madsholme** [kurokobo/awx-on-k3s#395]
I don't know if this is OK to ask here, but would there be anything wrong with using this k3 cluster deployment with awx to install Harbour as a way to provide execution environments images for the awx? I know you have a guide for using a private image repo but I would prefer something with a web ui aswell, so would there be anything wrong installing harbor running on a diffrent port?

**Comment by kurokobo** [comment]
@madsholme 
Technically there is no problem to install both AWX and Harbor on the same K3s nodes. Of course there must be enough computing resources (CPU and RAM) and storage, but you can make them work correctly by configuring them correctly.

**Comment by madsholme** [comment]
@kurokobo thanks for making that clear. Guess I know what to do tonight 😅

**Comment by kurokobo** [comment]
If you are familier with Helm, this chart may help you: https://github.com/goharbor/harbor-helm

**Comment by madsholme** [comment]
@kurokobo not really but I always understood it as a docker compose alternative. Guess it's time to dig into helm now. Thanks for the link

**Comment by kurokobo** [comment]
As long as you configure them to avoid conflicts with the exported ports, it is technically possible to run Docker on the same node as K3s, with AWX running on K3s and Harbor on Docker.

Either way, it's great to tackle new things. Good luck!

**Comment by madsholme** [comment]
@kurokobo might aswell do it right 😊 thanks for the input.

**Comment by kurokobo** [comment]
I don't have any plan to provide the guide to install Harbor on K3s so I'm closing this issue, have fun with AWX and Ansible 👍
