### ISSUE TITLE
AWX backup cleanup

### ISSUE THREAD

**Issue by rexberg** [kurokobo/awx-on-k3s#399]
Hello kurokobo !

First I want to thank you so much for this awesome repo that you have created!

I use your backup solution for AWX (in AWX) with some minor modifications. It works really well for what it does. I have one question regarding the cleanup of old backups, this part:
https://github.com/kurokobo/awx-on-k3s/blob/5bed268e03c45029766df4f49d969f8ba40c36e9/backup/ansible/project/backup.yml#L89

It seems that only the `AWXBackup` objects gets removed and not the actual data inside the PVC. Is this the intended behavior? If so, do you have a suggestion on how the `tower-openshift-backup-YYYY-MM-DD-HHMMSS` directories can also be removed? I will also look into this as well and if I come up with anything I will share it in this issue.

Cheers!

**Comment by kurokobo** [comment]
@rexberg 
Hi, thanks for using my repo!

> It seems that only the AWXBackup objects gets removed and not the actual data inside the PVC. Is this the intended behavior?

My playbook passes `clean_backup_on_delete: true` to AWXBackup resource which allows it to deletes actual backup files in the PVC when AWXBackup resource is removed.
There is a description about this parameter in my README.md, please search `clean_backup_on_delete` in the page in:
- My README.md : https://github.com/kurokobo/awx-on-k3s/tree/main/backup/ansible
- Official docs: https://github.com/ansible/awx-operator/tree/devel/roles/backup

**Comment by rexberg** [comment]
I somehow missed the `clean_backup_on_delete: true` setting. That solves it.

Thanks @kurokobo
