### ISSUE TITLE
Suggestion: Documentation of Storage Requirements

### ISSUE THREAD

**Issue by unixsysadmin** [kurokobo/awx-on-k3s#42]
## Environment

OS: RHEL 8.5
Kubernetes/K3s: v1.22.6+k3s1 (3228d9cb)
AWX Operator: 0.16.1

## Description
It may be helpful for new users to this project to be aware of the storage requirements - perhaps in the "Prepare CentOS 8 host" section - as I ran into a couple of problems when I first started using this repository.

### /var/lib/rancher
I ran out of room in `/var` as it is on a dedicated filesystem.  I've since created a `/var/lib/rancher` filesystem which on my base AWX install consumes around 5.6GB of space.  I'm unsure if this is going to grow and by how much - is it possible to make a reference to this directory/filesystem and perhaps some initial sizing suggestions?

### File permissions
Our build has a restrictive umask, so my /data directories were different from yours.

```
drwxr-x---. 3 root root 18 Feb 16 09:07 /data/postgres
drwxr-x---. 2 root root  6 Feb 16 09:07 /data/postgres/data
drwxr-x---. 2 1000 root  6 Feb 16 09:07 /data/projects
```

However, I followed the steps https://github.com/kurokobo/awx-on-k3s/blob/main/tips/troubleshooting.md#the-pod-for-postgresql-is-in-crashloopbackoff-state-and-shows-permission-denied-log which resolved the issue.  I now perform the following on a fresh install:

```
sudo chmod 755 /data/postgres /data/postgres/data
```

Is it worth adding that to the setup docs as it seems like a firm requirement?

### /data 
I created a /data filesystem for my environment - again, unsure if that should be documented.  However, I did see this in the base configuration:

```
  postgres_storage_class: awx-postgres-volume
  postgres_storage_requirements:
    requests:
      storage: 2Gi
```
If a database grows more than this size, is it simply a case of updating that file and running `kubectl apply -k base`

## Step to Reproduce

Follow the deployment guide on a freshly installed Operating System.

**Comment by kurokobo** [comment]
Good point, thanks for filling this issue.
Basically, I don't want to overly flesh out the guide, but there might be some points that should be added.

> /var/lib/rancher

It's a bit difficult to calculate actual storage requirement of this directory as this will be used to save snapshots of overlayfs and will be grown during pod's lifetime. I guess 10 GiB is enough to flesh install but I have no evidence just now

> File permissions

I have no umask in my environment so the directories had been created with `755` by default, but will consider adding `sudo chmod 755 /data/postgres` to the guide.

> /data

The value of `storage` of the PVs with type `hostPath` which used in this repo are just like "label" and never be used as actual capacity limitation, so your PVs have no capacity limit.

> There is no limit on how much space an emptyDir or hostPath volume can consume
> https://kubernetes.io/docs/concepts/storage/volumes/#resources

Therefore no modification for PV and PVCs is required  even if the DB will be over grown. Just care of the free space of the filesystem which `/data` exists on your K3s host.

**Comment by unixsysadmin** [comment]
Thanks - the above is really useful.

Understood that you don't want complicate the guide - it's very good at the moment IMO and I've just deployed AWX 20 using the latest operator, used the guides for HTTP to HTTPS redirection and applied the configuration changes for provisioning callbacks.

Probably some words about `/var/lib/rancher` consuming space will be enough to stop someone new to the project from running into trouble on the first attempt.

Now I need to get my head around custom execution environments!

**Comment by kurokobo** [comment]
Added:
- [Requirements in `README.md`](https://github.com/kurokobo/awx-on-k3s#requirements)
- `sudo chmod 755 /data/postgres`

Thanks for filling suggestions
