### ISSUE TITLE
subject in RoleBinding missing namespace

### ISSUE THREAD

**Issue by seadoox** [kurokobo/awx-on-k3s#53]
The RoleBinding created in the rbac/sa.yaml file seems to be missing the namespace in the subjects section. Without adding that I got authorization failures.

![image](https://user-images.githubusercontent.com/1318460/157737255-c0e62747-54f8-41cf-b46a-98157119a2bc.png)

**Comment by kurokobo** [comment]
Yep, so [the commands in the guide](https://github.com/kurokobo/awx-on-k3s/tree/main/backup/ansible#prepare-service-account-and-api-token) includes `-n ${NAMESPACE}` option.

```bash
$ NAMESPACE=awx
$ kubectl -n ${NAMESPACE} apply -f rbac/sa.yaml
```

This will create `RoleBinding` in `awx` namespace and will subject to `awx-backup` service account in `awx` namespace.
