### ISSUE TITLE
Clarification on mode for /etc/rancher/k3s/k3s.yaml / --write-kubeconfig-mode 644 in install guide

### ISSUE THREAD

**Issue by ThePVD** [kurokobo/awx-on-k3s#58]
Hello!  Your project has been very useful for us in creating running AWX environments.

I have an environment where we are considering "locking down" kubectl interactions to root user, so am contemplating changing kubeconfig mode to 600/640.  Is there risk to doing so?  I do not understand the architecture well enough to understand why this kubeconfig file is made readable to non-root users in guide.

Thank you for your consideration.

**Comment by kurokobo** [comment]
@ThePVD 
Thanks for using my repository :)
It is safe to change permissions.
If set it to 600 or 640, any operations with the `kubectl` command will not be allowed except for the root user. But there are no other side effects.

**Comment by ThePVD** [comment]
Spectacular, thank you again for your work and response.
