### ISSUE TITLE
Bastion host on k3s

### ISSUE THREAD

**Issue by fferraro87** [kurokobo/awx-on-k3s#64]
## Environment

- OS: Ubuntu 20.04
- Kubernetes/K3s: k3s v1.22.7+k3s1
- AWX Operator: 0.20

## Description
Create a bastion host for all hosts of my inventories

that's not an issue at all, but do you have a way to implement use of a bastion host on k3s for all hosts on my inventories used on awx?

**Comment by kurokobo** [comment]
@fferraro87 
Hmm, let me know detailed requirements. Why do you want to use bastion? What's your use case?

**Comment by fferraro87** [comment]
i need to use a bastion because in order to connect to every single host on my inventories i need to made a sshpass on a vm that's my ssh bridge to my infrastructure

**Comment by kurokobo** [comment]
If you need a Pod to take the place of your bastion VM, technicaly you can create the Pod which runs `sshd` with a volume that contains required files for SSH. To do this you need to build your own container image that can be used as a bastion Pod, and write your own manifest files for the Deployment, Service, PV, and PVC.

I've not tried but I think there is a chance to use [`kubernetes.core.kubectl` connection plugin](https://docs.ansible.com/ansible/latest/collections/kubernetes/core/kubectl_connection.html#ansible-collections-kubernetes-core-kubectl-connection) to use specific Pod as bastion.

Anyway it's a bit hard to provide guides sinse this is totally out of scope of my repo.
