### ISSUE TITLE
feat: bump AWX to 21.0.0 and operator version to 0.20.1

### ISSUE THREAD

**Issue by unixsysadmin** [kurokobo/awx-on-k3s#65]
I noticed that new versions of AWX and the AWX Operator were released yesterday:

[AWX Operator 0.20.1](https://github.com/ansible/awx-operator/releases/tag/0.20.1)
[AWX 21.0.0](https://github.com/ansible/awx/releases/tag/21.0.0)

It would be great if you could bump the revisions in your repo to support this.  Happy to help test this - a couple of bugs in AWX 20 as you've commented on (https://github.com/ansible/awx/issues/11765) were causing problems for us, so it would be great to upgrade.

**Comment by kurokobo** [comment]
Thanks for the heads-up, I've also received notifications that new version has been released for AWX and AWX Operator yesterday.

I was one of those who were eagerly waiting for the problem to be solved, so of course I have a plan to update my repo. It will be done today or tomorrow 😄

**Comment by kurokobo** [comment]
@unixsysadmin 
Tested with the latest operator and updated my repo. Will close this issue 😃 Thanks!
