### ISSUE TITLE
Question regarding SSL

### ISSUE THREAD

**Issue by nicolaibaralmueller** [kurokobo/awx-on-k3s#68]
Hi,

I've manually created the DNS record in Azure and usually acme can create certificate without the need to define azure resources. Why is the Issuer part needed? The concept is not clear to me. A public IP with access via port 80/http should be enough. Thanks in advance

**Comment by kurokobo** [comment]
In ACME protocol, there are three methods to validate domain to issue certificate.

- HTTP-01
- TLS-ALPN-01
- DNS-01

Refer this page for details for each methods: <https://letsencrypt.org/docs/challenge-types/>

> I've manually created the DNS record in Azure and usually acme can create certificate without the need to define azure resources.
> A public IP with access via port 80/http should be enough.

This is _HTTP-01_ method. For HTTP-01 or TLS-ALPN-01, yes, you're right. You can issue your cert without the need to define any azure resources like TXT records.

But in my guide, _DNS-01_ is used. The advantage of DNS-01 is that certificates can be issued even for services that do not want to expose port 80 or 443 to the Internet. This is useful, for example, when you want to publish some web services using a valid (not self-signed) certificate only within some private (internal) network.

**Comment by nicolaibaralmueller** [comment]
Thanks for the in depth explanation which was too the point and easy to understand.
