### ISSUE TITLE
SSL Certificate error

### ISSUE THREAD

**Issue by nicolaibaralmueller** [kurokobo/awx-on-k3s#70]
Hi,

Followed your guide and AWX installs without errors according to the install logs. Using a VM in Azure with no ports open to the internet.

Certificate error: CA Root certificate not trusted, issuer is TRAEFIK DEFAULT CERT

The service principal is DNS Zone Contributor in the Azure DNS zone.

Any specific logs one should look at?

**Comment by kurokobo** [comment]
> Certificate error: CA Root certificate not trusted, issuer is TRAEFIK DEFAULT CERT

When and where you got this error? Provide more information about your environment and steps to reproduce.

This page is also helpful: <https://cert-manager.io/docs/faq/acme/>

**Comment by nicolaibaralmueller** [comment]
Nevermind. RG was wrong and thus was unable to create the cert. 

If anybody else have problems the command is: `kubectl get -n awx challenges`

Your guide works as a charm as usual.
