### ISSUE TITLE
"make deploy" dont work

### ISSUE THREAD

**Issue by tjanitsc** [kurokobo/awx-on-k3s#77]
## Environment

- OS: CentOS X.Y, RHEL X.Y, Ubuntu X.Y, Debian X.Y, ...
- Kubernetes/K3s: X.Y.Z
- AWX Operator: X.Y.Z

## Description

Blah blah blah ...

## Step to Reproduce

1. Deploy ...
2. Invoke `kubectl ...`
3. ...
4. ...

**Comment by kurokobo** [comment]
If you need help, please provide enough information for others to understand your situation.

**Comment by hoanbc** [comment]
You need add link kubectl to environment 

cat /root/.bash_profile
# User specific environment and startup programs
PATH=$PATH:$HOME/bin:/usr/local/bin/
