### ISSUE TITLE
Enterprise SSL Certificate

### ISSUE THREAD

**Issue by smccloud** [kurokobo/awx-on-k3s#83]
## Environment
- OS: RockyLinux 8.6
- Kubernetes/K3s: v1.23.6+k3s1 (418c3fa8)
- AWX Operator: 0.22.0

## Description
I deployed using a self-signed SSL certificate using
AWX_HOST="awx.example.com"
openssl req -x509 -nodes -days 3650 -newkey rsa:2048 -out ./base/tls.crt -keyout ./base/tls.key -subj "/CN=${AWX_HOST}/O=${AWX_HOST}" -addext "subjectAltName = DNS:${AWX_HOST}"
However, I would like to switch it to an enterprise CA signed SSL certificate.  Do I just need generate a new certificate and key using my enterprise CA using the same names, place them in the same spot, then run kubectl apply -k base to apply the new certificate and private key?

**Comment by kurokobo** [comment]
@smccloud 
Hi, thanks for filling the issue.

> Do I just need generate a new certificate and key using my enterprise CA using the same names, place them in the same spot, then run kubectl apply -k base to apply the new certificate and private key?

Correct. To be more specifically:

1. Generate private key (A) and CSR on the K3s host
2. Send CSR to your CA
3. Receive CA-signed server certificate (B) from your CA
4. Put your private key (A) and certificate (B) to your Ingress, by renaming them to `tls.crt` and `tls.key` and replacing old self-signed one, then `kubectl apply -k base`.

Note that both your private key (A) and certificate (B) has to have PEM format. You may need to ask the CA to create a certificate in PEM format, or convert it to PEM format yourself.

I'm closing this issue but please feel free to re-open if you have further questions.
