### ISSUE TITLE
Custom certificate for AWX can't be applied

### ISSUE THREAD

**Issue by smccloud** [kurokobo/awx-on-k3s#87]
@smccloud 
Hi, thanks for filling the issue.

> Do I just need generate a new certificate and key using my enterprise CA using the same names, place them in the same spot, then run kubectl apply -k base to apply the new certificate and private key?

Correct. To be more specific:

1. Generate private key (A) and CSR on the K3s host
2. Send CSR to your CA
3. Receive CA-signed server certificate (B) from your CA
4. Put your private key (A) and certificate (B) to your Ingress, by renaming them to `tls.crt` and `tls.key` and replacing old self-signed one, then `kubectl apply -k base`.

Note that both your private key (A) and certificate (B) has to have PEM format. You may need to ask the CA to create a certificate in PEM format, or convert it to PEM format yourself.

I'm closing this issue but please feel free to re-open if you have further questions.

_Originally posted by @kurokobo in https://github.com/kurokobo/awx-on-k3s/issues/83#issuecomment-1149810420_

I just got time to do this, it is now showing as a TRAEFIK DEFAULT CERT self-signed certificate instead of the local enterprise CA-signed certificate I created.  Do you know why it would ignore the one I made and use a different certificate to present it?

**Comment by kurokobo** [comment]
Some possibilities are here:

- The CN or SAN in your cert does not match hostname in Ingress resource
- The certificate and key are not paired correctly
- The certificate and/or key has not PEM format
- The certificate and key were not replaced correctly for `kubectl apply -k base`, or the file name is incorrect.

**Comment by kurokobo** [comment]
I've modified the subject for this issue.
The next time you create an issue, please describe the problem briefly in the subject.

**Comment by smccloud** [comment]
I think I figured out what I did.  I'm so used to having to chain our CA's root certificate that I was doing that.  I tried again without doing that and it is now working correctly.  Moral of the story, do not chain the root certificate.

**Comment by kurokobo** [comment]
@smccloud 
Good to hear that, thanks for updating🥳
Have fun!
