### ISSUE TITLE
Image Pull Error When Running AWX Jobs - No internet

### ISSUE THREAD

**Issue by everydaylearner** [kurokobo/awx-on-k3s#93]
Hello,
I successfully deployed awx-on-k3s. It is working perfectly well in the lab environment.

I exported the VM i have in the lab environment and moved to the production environment successfully.  However in the production environment. When i run AWX jobs. i am getting "Error creating pod: container failed to start, ImagePullbackOff"  error.  We dont have internet access in the prod environment.

Does AWX now creates a new POD each time we run a job? and does it pull directly from the internet? Is there a way have it pull from local cache etc? 

Thank you!

**Comment by kurokobo** [comment]
Hi, 

> Does AWX now creates a new POD each time we run a job?

Yes, AWX creates a new pod each time.

> and does it pull directly from the internet?

Depends on your configuration. You can change **imagePullPolicy** (It is an important term in Kubernetes) via EE configuration page.

![image](https://user-images.githubusercontent.com/2920259/173962470-c16b8282-359c-45eb-87b1-be0f9380b1f5.png)

Refer the documentation for Kubernetes for detail: https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy

> Is there a way have it pull from local cache etc?

If your EE has been configured as `IfNotPresent` and if your `containerd` has the image locally, existing image will be re-used. You can the list of the cached image by `sudo /usr/local/bin/k3s crictl images`.

Alternatively, you can [deploy a container registry locally](https://github.com/kurokobo/awx-on-k3s/tree/main/registry) and push EE images to it, and use it.

**Comment by kurokobo** [comment]
Alternatively, you can deploy a container registry to K3s and push EE images to it for use from AWX: https://github.com/kurokobo/awx-on-k3s/tree/main/registry

**Comment by everydaylearner** [comment]
@kurokobo thank you very much for this! Appreciate it!
