### ISSUE TITLE
Troubleshooting hint about Ingress issue out of date?

### ISSUE THREAD

**Issue by TheBigBear** [kurokobo/awx-on-k3s#98]
## Environment

- OS: AlmaLinux 8.6 binary compatible to CentOS 8.6
- Kubernetes/K3s: v1.23.6+k3s1 (418c3fa8) go version go1.17.5
- AWX Operator: git tag 0.23.0

## Description

Troubleshooting hint on Ingress problems tells us two steps to #1 add a ```/var/lib/rancher/k3s/server/manifests/traefik-config.yaml``` and that first step works well.
BUT it then says step #2:

```
"The last step is modifying AWX. By default, AWX uses only `REMOTE_ADDR` and `REMOTE_HOST` headers to determine the remote host (means HTTP client). Therefore, you have to make AWX to use `X-Forwarded-For` header.

Modify your `base/awx.yaml` and add following three lines."

```
```
spec:
    ...
    extra_settings:     👈👈👈
    - setting: REMOTE_HOST_HEADERS     👈👈👈
        value: "['HTTP_X_FORWARDED_FOR', 'REMOTE_ADDR', 'REMOTE_HOST']"     👈👈👈
```

Then apply this change and wait for your AWX will be reconfigured.

```bash
kubectl apply -k base
```

But that returns:

```
error: accumulating resources: accumulation err='accumulating resources from 'awx.yaml': yaml: line 51: mapping values are not allowed in this context': got file 'awx.yaml'
```

and line 51 corresponds to the 3rd line, the 'value' line above

## Step to Reproduce

1. amend the base/awx.yaml file as per troubleshooting.md Ingress section
2. run ```kubectl apply -k base```

**Comment by kurokobo** [comment]
@TheBigBear 
Thanks for reporting this, sorry it's my fault, it's indentation issue.

This is the corrected example; Add two spaces before `- settings` (or remove two spaces before `value:` is also acceptable).

```yaml
spec:
    ...
    extra_settings:     👈👈👈
      - setting: REMOTE_HOST_HEADERS     👈👈👈
        value: "['HTTP_X_FORWARDED_FOR', 'REMOTE_ADDR', 'REMOTE_HOST']"     👈👈👈
```

Will update my guide 😃

**Comment by kurokobo** [comment]
@TheBigBear 
Hi, according to the comment in the gist, seems there are some misconfigured hostname.

> But if I try to connect to my k3s node with https://awx.example.com I get     👈👈👈
> 
> ```
> Bad gateway
> ```

> ```
> k3s kubectl describe ingress awx-ingress -n awx
> Name:             awx-ingress
> Labels:           app.kubernetes.io/component=awx
>                   app.kubernetes.io/managed-by=awx-operator
>                   app.kubernetes.io/name=awx
>                   app.kubernetes.io/operator-version=0.23.0
>                   app.kubernetes.io/part-of=awx
> Namespace:        awx
> Address:          10.10.97.50
> Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
> TLS:
>   awx-secret-tls terminates awx.example.com     👈👈👈
> Rules:
>   Host            Path  Backends
>   ----            ----  --------
>   awx.ict.om.org     👈👈👈
>                   /   awx-service:80 (10.42.0.12:8052)
> Annotations:      <none>
> Events:           <none>
> ```

If you want to access your AWX via `https://awx.example.com`, all of above have to be `awx.example.com`, but your ingress has different hostname `awx.ict.om.org`.

**Comment by kurokobo** [comment]
@TheBigBear 
Hi, any update on this?

**Comment by kurokobo** [comment]
Closing "due to inactivity.
